# Generated by Django 5.2.10 on 2026-01-22 13:37

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import portal.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Auto-generated cryptographically secure username",
                        max_length=15,
                        unique=True,
                    ),
                ),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "role_code",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("employee", "Employee"),
                            ("super", "Super"),
                            ("distributor", "Distributor"),
                            ("retailer", "Retailer"),
                            ("customer", "Customer"),
                            ("vendor", "Vendor"),
                        ],
                        help_text="User role code (required)",
                        max_length=20,
                    ),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_login_user_agent", models.TextField(blank=True, null=True)),
                ("login_count", models.IntegerField(default=0)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("kyc_completed", models.BooleanField(default=False)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("mfa_configured", models.BooleanField(default=False)),
                (
                    "mfa_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("otp", "OTP (SMS)"),
                            ("authenticator", "Authenticator App"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("totp_secret", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "portal_user",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("aadhaar", "Aadhaar"),
                            ("pan", "PAN"),
                            ("passport", "Passport"),
                            ("driving_license", "Driving License"),
                            ("voter_id", "Voter ID"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=50)),
                (
                    "document_files",
                    models.JSONField(
                        default=list, help_text="List of S3 URLs for document files"
                    ),
                ),
                (
                    "verification_vendor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cashfree", "Cashfree"),
                            ("invincible_ocean", "Invincible Ocean"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "verification_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "verification_response",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_kycs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC",
                "verbose_name_plural": "KYCs",
                "db_table": "portal_kyc",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("b2b", "B2B"), ("b2c", "B2C")], max_length=10
                    ),
                ),
                ("hierarchy_level", models.IntegerField(default=0)),
                ("mfa_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "portal_role",
                "ordering": ["-hierarchy_level", "name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="portal.role",
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("frozen", "Frozen"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("encrypted_seed_phrase", models.TextField(blank=True, null=True)),
                (
                    "wallet_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "portal_wallet",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Required. User's first name.", max_length=150
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="User profile photo",
                        null=True,
                        upload_to="profiles/photos/",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, default="Indian", max_length=100, null=True
                    ),
                ),
                (
                    "country_of_residence",
                    models.CharField(
                        blank=True, default="India", max_length=100, null=True
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("address_line_1", models.TextField(blank=True, null=True)),
                ("address_line_2", models.TextField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Required. User's email address. Must be unique.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Required. User's mobile number. Must be unique.",
                        max_length=15,
                        unique=True,
                        validators=[portal.utils.validators.validate_phone_number],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[portal.utils.validators.validate_phone_number],
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "account_holder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[("savings", "Savings"), ("current", "Current")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("encrypted_banking_details", models.TextField(blank=True, null=True)),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        help_text="PAN number (10 characters)",
                        max_length=10,
                        null=True,
                        validators=[portal.utils.validators.validate_pan_number],
                    ),
                ),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True,
                        help_text="Aadhaar number (12 digits)",
                        max_length=12,
                        null=True,
                        validators=[portal.utils.validators.validate_aadhaar_number],
                    ),
                ),
                ("gst_number", models.CharField(blank=True, max_length=15, null=True)),
                ("tax_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "language_preference",
                    models.CharField(blank=True, default="en", max_length=10),
                ),
                (
                    "timezone",
                    models.CharField(blank=True, default="Asia/Kolkata", max_length=50),
                ),
                (
                    "currency_preference",
                    models.CharField(blank=True, default="INR", max_length=3),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Notification preferences (email, SMS, push, etc.)",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="General user settings and preferences",
                    ),
                ),
                ("security_question_1", models.TextField(blank=True, null=True)),
                ("security_answer_1", models.TextField(blank=True, null=True)),
                ("security_question_2", models.TextField(blank=True, null=True)),
                ("security_answer_2", models.TextField(blank=True, null=True)),
                ("backup_codes", models.TextField(blank=True, null=True)),
                (
                    "recovery_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("last_password_change", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Mandatory profile for every user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "portal_profile",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="portal_prof_email_8fb243_idx"),
                    models.Index(fields=["phone"], name="portal_prof_phone_9a03f1_idx"),
                    models.Index(
                        fields=["status"], name="portal_prof_status_f5a6f4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Permission",
                "verbose_name_plural": "User Permissions",
                "db_table": "portal_user_permission",
                "ordering": ["-granted_at"],
                "unique_together": {("user", "permission")},
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=20)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("encrypted_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="portal.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "db_table": "portal_wallet_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"],
                        name="portal_wall_wallet__2f2f10_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="portal_wall_status_c78b89_idx",
                    ),
                ],
            },
        ),
    ]
