# Generated by Django 5.2.10 on 2026-01-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_completion_required",
            field=models.BooleanField(
                default=False,
                help_text="True if user must complete profile details (e.g., after social signup)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("apple", "Apple"),
                ],
                help_text="Social provider used for signup/login",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_provider_id",
            field=models.CharField(
                blank=True,
                help_text="User ID from social provider",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Account locked until this timestamp (30 minutes after 10 failed attempts)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive failed login attempts"
            ),
        ),
    ]
