# Generated by Django 5.2.10 on 2026-01-25 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_add_user_email_first_name_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the log entry was created')),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, help_text='Log severity level', max_length=10)),
                ('category', models.CharField(choices=[('api', 'API'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20)),
                ('message', models.TextField(help_text='Log message')),
                ('module_name', models.CharField(blank=True, db_index=True, help_text='Module where event occurred', max_length=200, null=True)),
                ('url', models.CharField(blank=True, db_index=True, help_text='URL path for the request', max_length=500, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Request ID for tracing', max_length=100, null=True)),
                ('response_id', models.CharField(blank=True, help_text='Response ID', max_length=100, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, db_index=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Session ID', max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional structured data (sanitized)', null=True)),
                ('traceback', models.TextField(blank=True, help_text='Error traceback (for errors only)', null=True)),
                ('exception_type', models.CharField(blank=True, help_text='Exception type if error occurred', max_length=200, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False, help_text='Whether this log entry has been resolved/reviewed')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this log was resolved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this log entry', null=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved this log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'portal_log_entry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'log_level'], name='portal_log__timesta_105a24_idx'), models.Index(fields=['category', '-timestamp'], name='portal_log__categor_d43179_idx'), models.Index(fields=['user', '-timestamp'], name='portal_log__user_id_be67b0_idx'), models.Index(fields=['request_id'], name='portal_log__request_b7ab03_idx'), models.Index(fields=['resolved', '-timestamp'], name='portal_log__resolve_0722f9_idx')],
            },
        ),
    ]
