# Generated by Django 5.2.10 on 2026-01-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_add_ticket_management_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agent',
            new_name='portal_agen_departm_4f524e_idx',
            old_name='portal_agent_dept_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='portal_agen_is_avai_75ea76_idx',
            old_name='portal_agent_avail_tickets_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='portal_depa_is_acti_58273b_idx',
            old_name='portal_dept_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='portal_tick_status_e5e493_idx',
            old_name='portal_tick_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='portal_tick_priorit_76ab0d_idx',
            old_name='portal_tick_priorit_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='portal_tick_departm_d70500_idx',
            old_name='portal_tick_departm_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='portal_tick_assigne_6e04f7_idx',
            old_name='portal_ticket_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='portal_tick_created_326209_idx',
            old_name='portal_tick_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketassignmenthistory',
            new_name='portal_tick_ticket__7a8f57_idx',
            old_name='portal_tickhist_ticket_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketassignmenthistory',
            new_name='portal_tick_assigne_e10af6_idx',
            old_name='portal_tickhist_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketattachment',
            new_name='portal_tick_ticket__776d04_idx',
            old_name='portal_tickattach_ticket_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketnote',
            new_name='portal_tick_ticket__bde117_idx',
            old_name='portal_ticknote_ticket_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketnote',
            new_name='portal_tick_is_inte_75747b_idx',
            old_name='portal_ticknote_internal_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role_code',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('super', 'Super'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('support_agent', 'Support Agent'), ('dept_manager', 'Department Manager'), ('api_partner', 'API Partner'), ('partner', 'Partner'), ('super_distributor', 'Super Distributor')], help_text='User role code (required)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
