# Generated by Django 5.2.10 on 2026-01-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_add_vendor_config_to_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('kaleyra', 'Kaleyra API'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
    ]
