# Generated by Django 5.2.10 on 2026-01-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_add_gift_voucher_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Bank account holder name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='agreement_document',
            field=models.URLField(blank=True, help_text='S3 URL for signed agreement document', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='agreement_signed',
            field=models.BooleanField(default=False, help_text='Whether agreement has been signed'),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='agreement_signed_at',
            field=models.DateTimeField(blank=True, help_text='When agreement was signed', null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='bank_account_number',
            field=models.TextField(blank=True, help_text='Encrypted bank account number', null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, help_text='Bank IFSC code', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='bank_statement',
            field=models.URLField(blank=True, help_text='S3 URL for bank statement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='business_registration_doc',
            field=models.URLField(blank=True, help_text='S3 URL for business registration document', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='business_type',
            field=models.CharField(blank=True, choices=[('LLP', 'Limited Liability Partnership'), ('PRIVATE_LTD', 'Private Limited'), ('PUBLIC_LTD', 'Public Limited'), ('PARTNERSHIP', 'Partnership'), ('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('HUF', 'Hindu Undivided Family'), ('OTHER', 'Other')], help_text='Type of business entity', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='gst_certificate',
            field=models.URLField(blank=True, help_text='S3 URL for GST certificate', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GSTIN (GST Number)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='onboarding_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved the onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When onboarding was completed and approved', null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='onboarding_notes',
            field=models.TextField(blank=True, help_text='Admin notes during onboarding review', null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='onboarding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Brand onboarding status', max_length=20),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='other_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of other document S3 URLs with metadata'),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='pan_document',
            field=models.URLField(blank=True, help_text='S3 URL for PAN document', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN (Permanent Account Number)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When onboarding was rejected', null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for onboarding rejection', null=True),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Whether terms and conditions have been accepted'),
        ),
        migrations.AddField(
            model_name='giftvoucherbrand',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When terms were accepted', null=True),
        ),
        migrations.AlterField(
            model_name='giftvoucherbrand',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='INACTIVE', help_text='Brand status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='giftvoucherbrand',
            index=models.Index(fields=['onboarding_status'], name='portal_gift_onboard_c51190_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucherbrand',
            index=models.Index(fields=['status', 'onboarding_status'], name='portal_gift_status_09c416_idx'),
        ),
    ]
