# Generated by Django 5.2.10 on 2026-01-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_add_batch_processing_lock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Batch processing metadata including voucher progress tracking'),
        ),
    ]
