# Generated by Django 5.2.10 on 2026-01-27 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(help_text='User-friendly name for this API key', max_length=100)),
                ('api_key', models.CharField(db_index=True, help_text='Hashed API key (never store plain text)', max_length=255, unique=True)),
                ('api_secret', models.CharField(help_text='Hashed secret for HMAC signing', max_length=255)),
                ('key_prefix', models.CharField(help_text="Key prefix for identification (e.g., 'psk_live_')", max_length=20)),
                ('key_type', models.CharField(choices=[('LIVE', 'Live'), ('TEST', 'Test'), ('SANDBOX', 'Sandbox')], db_index=True, default='LIVE', help_text='Type of API key', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', help_text='API key status', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Service-level permissions')),
                ('rate_limit', models.JSONField(blank=True, default=dict, help_text='Per-service rate limits')),
                ('ip_whitelist', models.JSONField(blank=True, default=list, help_text='Allowed IP addresses (empty list = allow all)')),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for notifications', null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook secret for signature verification', max_length=255, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this API key was used', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Expiration date (null = never expires)', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this key was revoked', null=True)),
                ('revoked_reason', models.TextField(blank=True, help_text='Reason for revocation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'portal_api_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, help_text='API endpoint called', max_length=200)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('status_code', models.IntegerField(db_index=True, help_text='HTTP status code')),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of the request')),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=500, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Request ID for tracing', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this request was made')),
            ],
            options={
                'verbose_name': 'API Key Usage Log',
                'verbose_name_plural': 'API Key Usage Logs',
                'db_table': 'portal_api_key_usage_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(db_index=True, help_text='Auto-generated partner identifier code', max_length=20, unique=True)),
                ('company_name', models.CharField(help_text='Business/Company name', max_length=255)),
                ('contact_person', models.CharField(help_text='Primary contact person name', max_length=255)),
                ('email', models.EmailField(db_index=True, help_text='Business email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('business_type', models.CharField(choices=[('LLP', 'Limited Liability Partnership'), ('PRIVATE_LTD', 'Private Limited'), ('PUBLIC_LTD', 'Public Limited'), ('PARTNERSHIP', 'Partnership'), ('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('HUF', 'Hindu Undivided Family'), ('OTHER', 'Other')], help_text='Type of business entity', max_length=50)),
                ('gst_number', models.CharField(blank=True, help_text='GST registration number (optional)', max_length=15, null=True)),
                ('address', models.TextField(help_text='Business address')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Partner status', max_length=20)),
                ('onboarding_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Onboarding status', max_length=20)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, help_text='When onboarding was completed and approved', null=True)),
                ('onboarding_notes', models.TextField(blank=True, help_text='Admin notes during onboarding review', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional partner data and configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reseller Partner',
                'verbose_name_plural': 'Reseller Partners',
                'db_table': 'portal_reseller_partner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='giftvoucher',
            name='gv_metadata_gin_idx',
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this API key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikeyusagelog',
            name='api_key',
            field=models.ForeignKey(help_text='API key used for this request', on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='portal.apikey'),
        ),
        migrations.AddField(
            model_name='resellerpartner',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this partner record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reseller_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resellerpartner',
            name='onboarding_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved the onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reseller_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resellerpartner',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Partner wallet for transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_partners', to='portal.wallet'),
        ),
        migrations.AddField(
            model_name='apikeyusagelog',
            name='partner',
            field=models.ForeignKey(help_text='Reseller partner who made this request', on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to='portal.resellerpartner'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='partner',
            field=models.ForeignKey(help_text='Reseller partner this API key belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='portal.resellerpartner'),
        ),
        migrations.AddIndex(
            model_name='resellerpartner',
            index=models.Index(fields=['partner_code'], name='portal_rese_partner_c25cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerpartner',
            index=models.Index(fields=['email'], name='portal_rese_email_7cfc30_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerpartner',
            index=models.Index(fields=['status', 'onboarding_status'], name='portal_rese_status_b6a47d_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerpartner',
            index=models.Index(fields=['onboarding_status', '-created_at'], name='portal_rese_onboard_906d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['api_key', '-created_at'], name='portal_api__api_key_effc94_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['partner', '-created_at'], name='portal_api__partner_7a9c88_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['endpoint', '-created_at'], name='portal_api__endpoin_e487bd_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['status_code', '-created_at'], name='portal_api__status__5dd8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['created_at'], name='portal_api__created_2c953f_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['api_key'], name='portal_api__api_key_e7bcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['partner', 'status'], name='portal_api__partner_6b38e0_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_type', 'status'], name='portal_api__key_typ_915bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['status', 'expires_at'], name='portal_api__status_3d0a19_idx'),
        ),
    ]
