# Generated by Django 5.2.10 on 2026-01-28 06:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_add_partner_pricing_accounting_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBPSBillerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(db_index=True, help_text='Biller category code (e.g., ELECTRICITY, WATER)', max_length=50, unique=True)),
                ('category_name', models.CharField(help_text='Biller category name', max_length=100)),
                ('category_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas'), ('MOBILE_PREPAID', 'Mobile Prepaid'), ('MOBILE_POSTPAID', 'Mobile Postpaid'), ('LANDLINE', 'Landline'), ('BROADBAND', 'Broadband'), ('DTH', 'DTH'), ('INSURANCE', 'Insurance'), ('LOAN', 'Loan'), ('CREDIT_CARD', 'Credit Card'), ('FASTAG', 'Fastag'), ('MUNICIPAL', 'Municipal'), ('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('OTHER', 'Other')], help_text='Type of biller category', max_length=50)),
                ('commission_type', models.CharField(choices=[('REVENUE_SHARE', 'Revenue Share'), ('MARKUP', 'Markup'), ('FIXED_COMMISSION', 'Fixed Commission')], default='REVENUE_SHARE', help_text='Type of commission model', max_length=20)),
                ('default_commission_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Default commission percentage for this category', max_digits=5)),
                ('default_fixed_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Default fixed commission for this category', max_digits=15)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Base cost for this biller category', max_digits=15)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this biller category is active')),
                ('description', models.TextField(blank=True, help_text='Description of this biller category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='BBPS service', limit_choices_to={'code': 'BBPS'}, on_delete=django.db.models.deletion.CASCADE, related_name='biller_categories', to='portal.service')),
            ],
            options={
                'verbose_name': 'BBPS Biller Category',
                'verbose_name_plural': 'BBPS Biller Categories',
                'db_table': 'portal_bbps_biller_category',
                'ordering': ['category_name'],
                'indexes': [models.Index(fields=['service', 'is_active'], name='portal_bbps_service_a22fef_idx'), models.Index(fields=['category_code', 'is_active'], name='portal_bbps_categor_a21b2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RBIRuleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='Name of the RBI rule', max_length=100)),
                ('rule_description', models.TextField(help_text='Description of the RBI rule')),
                ('rule_config', models.JSONField(default=dict, help_text="RBI rule configuration (e.g., {'charges_on': 'sender', 'max_amount': 10000})")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this rule is active')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this rule becomes effective')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When this rule expires (null = never expires)', null=True)),
                ('rbi_circular_reference', models.CharField(blank=True, help_text='RBI circular/notification reference', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rbi_rules', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service this RBI rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rbi_rules', to='portal.service')),
            ],
            options={
                'verbose_name': 'RBI Rule Configuration',
                'verbose_name_plural': 'RBI Rule Configurations',
                'db_table': 'portal_rbi_rule_configuration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'is_active'], name='portal_rbi__service_7738e4_idx'), models.Index(fields=['is_active', 'effective_from'], name='portal_rbi__is_acti_6331c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('PER_TRANSACTION', 'Per Transaction'), ('TIERED', 'Tiered Pricing')], default='FIXED', help_text='Type of cost model', max_length=20)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Base cost for the service (what we pay vendor)', max_digits=15)),
                ('cost_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost percentage (if cost_type is PERCENTAGE)', max_digits=5)),
                ('cost_per_transaction', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per transaction (if cost_type is PER_TRANSACTION)', max_digits=15)),
                ('tiered_cost', models.JSONField(blank=True, default=list, help_text="Tiered cost structure: [{'min': 0, 'max': 1000, 'cost': 2.5}, ...]")),
                ('provides_commission', models.BooleanField(default=False, help_text='Whether this service provides commission (e.g., AEPS, DMT, BBPS)')),
                ('commission_on', models.CharField(blank=True, help_text="Who gets commission (e.g., 'sender', 'receiver', 'partner')", max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this cost configuration is active')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this cost becomes effective')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When this cost expires (null = never expires)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this cost configuration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this cost', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_costs', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service this cost applies to', on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='portal.service')),
            ],
            options={
                'verbose_name': 'Service Cost',
                'verbose_name_plural': 'Service Costs',
                'db_table': 'portal_service_cost',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'is_active'], name='portal_serv_service_641eb1_idx'), models.Index(fields=['is_active', 'effective_from'], name='portal_serv_is_acti_c920fd_idx')],
            },
        ),
    ]
