# Generated by Django 6.0.1 on 2026-02-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_add_simple_history_tables'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__gte', 0)), name='portal_giftvoucher_current_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gte', 0)), name='portal_giftvoucher_original_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='portal_wallet_balance_non_negative'),
        ),
    ]
