# Generated by Django 6.0.1 on 2026-02-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_partner_vendor_assignments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resellerpartnerpricing',
            new_name='portal_rese_partner_ce812f_idx',
            old_name='portal_res_partner_servic_idx',
        ),
        migrations.AddField(
            model_name='historicalresellerpartnerpricing',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor-specific pricing (null = default for service)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='portal.apivendor'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('api_explorer', 'API Explorer Tests'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('cashfree_pg', 'Cashfree PG API'), ('kaleyra', 'Kaleyra API'), ('leegality', 'Leegality API'), ('mobikwik_bbps', 'Mobikwik BBPS API'), ('gift_voucher', 'Gift Voucher'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='partnervendorassignment',
            unique_together={('partner', 'service_code', 'vendor')},
        ),
    ]
