# Generated by Django 6.0.1 on 2026-02-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_add_user_permission_revoked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBPSOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biller_id', models.CharField(db_index=True, help_text='Biller ID (from Operators.xlsx)', max_length=100, unique=True)),
                ('op', models.CharField(blank=True, db_index=True, help_text='Mobikwik operator id (op) – numeric string or int', max_length=50, null=True)),
                ('name', models.CharField(help_text='Operator / Biller name', max_length=255)),
                ('category', models.CharField(db_index=True, help_text='Category e.g. ELECTRICITY, WATER, DTH', max_length=80)),
                ('view_bill', models.CharField(blank=True, help_text='ViewBill flag from sheet', max_length=50, null=True)),
                ('customer_label', models.CharField(default='Consumer ID', help_text='Label for consumer/customer ID field (Name/cn in sheet)', max_length=100)),
                ('regex', models.CharField(blank=True, help_text='Validation regex for consumer ID', max_length=500, null=True)),
                ('ad1', models.CharField(blank=True, max_length=500, null=True)),
                ('ad2', models.CharField(blank=True, max_length=500, null=True)),
                ('ad3', models.CharField(blank=True, max_length=500, null=True)),
                ('ad4', models.CharField(blank=True, max_length=500, null=True)),
                ('ad9', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_params', models.TextField(blank=True, help_text='Additional Params for payment API (JSON or text)', null=True)),
                ('bbps_enabled', models.BooleanField(db_index=True, default=True, help_text='BBPS Enabled in sheet (True/1/Yes)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether operator is active in app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BBPS Operator',
                'verbose_name_plural': 'BBPS Operators',
                'db_table': 'portal_bbps_operator',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'bbps_enabled', 'is_active'], name='portal_bbps_categor_a1ab08_idx')],
            },
        ),
    ]
