# Generated by Django 5.2.10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_add_parkpe_voucher_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkPeServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('voucher_allowed', models.BooleanField(default=True, help_text='User can pay with voucher balance')),
                ('pg_allowed', models.BooleanField(default=True, help_text='User can pay with PG (Razorpay/Cashfree)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ParkPe Service Config',
                'verbose_name_plural': 'ParkPe Service Configs',
                'db_table': 'portal_parkpe_service_config',
            },
        ),
        migrations.CreateModel(
            name='ParkPePaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree')], db_index=True, max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('service_code', models.CharField(blank=True, db_index=True, default='', help_text='Empty = voucher purchase; e.g. BBPS = PG for BBPS pay', max_length=50)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_key', models.CharField(blank=True, help_text='Config key for key/secret', max_length=100, null=True)),
                ('is_default_for_voucher_purchase', models.BooleanField(default=False, help_text='Use this config when creating voucher purchase orders (service_code empty)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ParkPe Payment Gateway Config',
                'verbose_name_plural': 'ParkPe Payment Gateway Configs',
                'db_table': 'portal_parkpe_payment_gateway_config',
            },
        ),
        migrations.CreateModel(
            name='ParkPePaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gateway', models.CharField(db_index=True, max_length=20)),
                ('order_id', models.CharField(db_index=True, help_text='PG order id (e.g. Razorpay order_id)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='PG payment_id after verify', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkpe_payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ParkPe Payment Order',
                'verbose_name_plural': 'ParkPe Payment Orders',
                'db_table': 'portal_parkpe_payment_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='parkpepaymentgatewayconfig',
            constraint=models.UniqueConstraint(fields=('gateway', 'service_code'), name='parkpe_pg_config_gateway_service_unique'),
        ),
        migrations.AddIndex(
            model_name='parkpepaymentorder',
            index=models.Index(fields=['user', '-created_at'], name='portal_park_user_id_8f2d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='parkpepaymentorder',
            index=models.Index(fields=['status', '-created_at'], name='portal_park_status_9a3c2e_idx'),
        ),
    ]
