# Generated by Django 5.2.10

from django.db import migrations


def seed_bbps_service_config(apps, schema_editor):
    ParkPeServiceConfig = apps.get_model('portal', 'ParkPeServiceConfig')
    if not ParkPeServiceConfig.objects.filter(service_code='BBPS').exists():
        ParkPeServiceConfig.objects.create(
            service_code='BBPS',
            voucher_allowed=True,
            pg_allowed=True,
            is_active=True,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_add_parkpe_app_management_models'),
    ]

    operations = [
        migrations.RunPython(seed_bbps_service_config, noop),
    ]
