# Generated by Django 6.0.1 on 2026-02-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_rename_portal_park_user_id_8f2d1b_idx_portal_park_user_id_3edfe8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ownership_declaration_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted the vehicle ownership declaration (audit trail)', null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('api_explorer', 'API Explorer Tests'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('cashfree_pg', 'Cashfree PG API'), ('kaleyra', 'Kaleyra API'), ('leegality', 'Leegality API'), ('mobikwik_bbps', 'Mobikwik BBPS API'), ('gift_voucher', 'Gift Voucher'), ('connect_vehicle', 'Connect Vehicle'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
    ]
