# Generated by Django 6.0.1 on 2026-02-12 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_add_vehicle_ownership_declaration_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRCUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(help_text='Unlock valid until this time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_vehicle_rc_unlocks', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_unlocks', to='portal.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle RC Unlock',
                'verbose_name_plural': 'Vehicle RC Unlocks',
                'db_table': 'portal_connect_vehicle_rc_unlock',
                'constraints': [models.UniqueConstraint(fields=('user', 'vehicle'), name='portal_connect_vehicle_rc_unlock_user_vehicle_unique')],
            },
        ),
    ]
