# Generated by Django 5.2.10 on 2026-02-12 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_add_connect_chat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('vehicle_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('scanner_phone_masked', models.CharField(blank=True, default='', max_length=32)),
                ('owner_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Connect Call Log',
                'verbose_name_plural': 'Connect Call Logs',
                'db_table': 'portal_connect_call_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='connect_blocked_until',
            field=models.DateTimeField(blank=True, help_text='If set, user is blocked from Connect (call/chat) until this time', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='connect_warning_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of Connect warnings issued (admin can increment)'),
        ),
        migrations.CreateModel(
            name='ConnectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason or description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_reports_made', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='portal.connectthread')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_reports', to='portal.ticket')),
            ],
            options={
                'verbose_name': 'Connect Report',
                'verbose_name_plural': 'Connect Reports',
                'db_table': 'portal_connect_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
