# Generated by Django 5.2.10 on 2026-02-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_add_connect_admin_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rc_view_paid_at',
            field=models.DateTimeField(blank=True, help_text='When owner paid from voucher (Rs 50) to view full RC; once set, RC is shown without verify', null=True),
        ),
    ]
