# Generated by Django 6.0.1 on 2026-02-16 07:03
# Data migration: reassign users with removed role_codes to employee, then delete deprecated Role records.

from django.db import migrations


# Role codes that are being removed (only these 7 kept: super_admin, admin, employee, super_distributor, distributor, retailer, customer)
DEPRECATED_ROLE_CODES = ('super', 'vendor', 'support_agent', 'dept_manager', 'api_partner', 'partner')


def migrate_users_and_remove_roles(apps, schema_editor):
    User = apps.get_model('portal', 'User')
    Role = apps.get_model('portal', 'Role')

    # Get or create employee role for reassignment
    employee_role = Role.objects.filter(code='employee').first()
    if not employee_role:
        # Create if missing (e.g. fresh DB)
        employee_role = Role.objects.create(
            name='Employee',
            code='employee',
            category='b2b',
            hierarchy_level=5,
            mfa_required=False,
        )

    # Reassign all users with deprecated role_code to employee
    updated = User.objects.filter(role_code__in=DEPRECATED_ROLE_CODES).update(
        role_code='employee',
        role=employee_role,
    )

    # Delete deprecated Role records
    Role.objects.filter(code__in=DEPRECATED_ROLE_CODES).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_add_partner_api_subscription'),
    ]

    operations = [
        migrations.RunPython(migrate_users_and_remove_roles, noop),
    ]
