# Generated by Django 6.0.1 on 2026-02-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0056_add_bbps_operator_circle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIncomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('COMMISSION', 'Commission'), ('MARKUP', 'Markup'), ('PER_TXN', 'Per Transaction')], default='COMMISSION', max_length=20)),
                ('rate_per_txn', models.DecimalField(blank=True, decimal_places=4, help_text='Fixed amount per transaction (INR)', max_digits=12, null=True)),
                ('rate_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of transaction amount', max_digits=5, null=True)),
                ('vendor_code', models.CharField(blank=True, help_text='e.g. mobikwik', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(limit_choices_to={'code__in': ['BBPS', 'VOUCHER', 'GIFT_VOUCHER']}, on_delete=django.db.models.deletion.CASCADE, related_name='income_configs', to='portal.service')),
            ],
            options={
                'verbose_name': 'Service Income Config',
                'verbose_name_plural': 'Service Income Configs',
                'db_table': 'portal_service_income_config',
                'ordering': ['service', 'vendor_code'],
            },
        ),
        migrations.CreateModel(
            name='HubVendorCostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(choices=[('sms', 'SMS'), ('ivr', 'IVR / Click-to-Call'), ('cashfree_pg', 'Cashfree PG'), ('cashfree_rc', 'Cashfree RC'), ('cashfree_kyc', 'Cashfree KYC')], db_index=True, max_length=30)),
                ('vendor_code', models.CharField(db_index=True, help_text='e.g. kaleyra, cashfree', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Cost in INR', max_digits=15)),
                ('unit_count', models.PositiveIntegerField(default=1, help_text='e.g. 1 SMS, 1 call')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('period_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_cost_records', to='portal.resellerpartner')),
            ],
            options={
                'verbose_name': 'Hub Vendor Cost Record',
                'verbose_name_plural': 'Hub Vendor Cost Records',
                'db_table': 'portal_hub_vendor_cost_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_code', 'period_date'], name='portal_hub__service_76d211_idx'), models.Index(fields=['vendor_code', 'created_at'], name='portal_hub__vendor__00c313_idx')],
            },
        ),
    ]
