# Generated by Django 5.2.10 on 2026-01-22 14:49

import portal.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", portal.models.UserManager()),
            ],
        ),
    ]
