# Generated by Django 5.2.10 on 2026-01-25 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_add_log_entry_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether department is active')),
                ('can_view_all_tickets', models.BooleanField(default=False, help_text="Whether department can view tickets from other departments")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text="User who created this department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'portal_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, help_text='Unique ticket identifier (e.g., TKT-20260125-001)', max_length=20, unique=True)),
                ('subject', models.CharField(help_text='Ticket subject', max_length=255)),
                ('description', models.TextField(help_text='Detailed ticket description')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], db_index=True, default='NEW', help_text='Current ticket status', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', help_text='Ticket priority level', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Ticket category', max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for ticket categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Agent assigned to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department handling this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='portal.department')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'portal_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, help_text='Whether agent is available for new ticket assignments')),
                ('max_tickets', models.IntegerField(default=10, help_text='Maximum number of tickets agent can handle simultaneously')),
                ('current_tickets', models.IntegerField(default=0, help_text='Current number of active tickets assigned to agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department this agent belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='portal.department')),
                ('user', models.OneToOneField(help_text='User who is an agent', on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'portal_agent',
                'unique_together': {('user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Note content')),
                ('is_internal', models.BooleanField(default=False, help_text='Whether this note is internal (not visible to customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(help_text='User who created this note', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='portal.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Note',
                'verbose_name_plural': 'Ticket Notes',
                'db_table': 'portal_ticket_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file', upload_to='ticket_attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='File MIME type', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ticket', models.ForeignKey(help_text='Ticket this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.ticket')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
                'db_table': 'portal_ticket_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason for assignment/reassignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who performed the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_from', models.ForeignKey(blank=True, help_text='Previous agent (if reassignment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_from', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='New agent assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_to', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='portal.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Assignment History',
                'verbose_name_plural': 'Ticket Assignment Histories',
                'db_table': 'portal_ticket_assignment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active', 'name'], name='portal_dept_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='portal_tick_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', '-created_at'], name='portal_tick_priorit_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', 'status'], name='portal_tick_departm_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='portal_ticket_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by', '-created_at'], name='portal_tick_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketnote',
            index=models.Index(fields=['ticket', '-created_at'], name='portal_ticknote_ticket_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketnote',
            index=models.Index(fields=['is_internal', '-created_at'], name='portal_ticknote_internal_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket', '-uploaded_at'], name='portal_tickattach_ticket_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['department', 'is_available'], name='portal_agent_dept_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_available', 'current_tickets'], name='portal_agent_avail_tickets_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignmenthistory',
            index=models.Index(fields=['ticket', '-created_at'], name='portal_tickhist_ticket_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignmenthistory',
            index=models.Index(fields=['assigned_to', '-created_at'], name='portal_tickhist_assigned_idx'),
        ),
    ]
