# Generated by Django 5.2.10 on 2026-01-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_increase_totp_secret_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., BBPS, AEPS)', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Service code (e.g., BBPS, AEPS)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Service description', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], db_index=True, default='pending', help_text='Service status', max_length=20)),
                ('api_provider', models.CharField(blank=True, help_text='API provider name', max_length=100, null=True)),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint URL', null=True)),
                ('api_key', models.CharField(blank=True, help_text='API key (encrypted)', max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, help_text='API secret (encrypted)', max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether service is enabled')),
                ('requires_kyc', models.BooleanField(default=True, help_text='Whether service requires KYC verification')),
                ('min_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum balance required', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'portal_service',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code', 'status'], name='portal_serv_code_e10c96_idx'), models.Index(fields=['is_enabled', 'status'], name='portal_serv_is_enab_38839f_idx')],
            },
        ),
    ]
