# Generated by Django 5.2.10 on 2026-01-25 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_add_service_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
        migrations.CreateModel(
            name='CashfreeAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the API call was made')),
                ('api_type', models.CharField(choices=[('pan', 'PAN Verification'), ('aadhaar', 'Aadhaar Verification'), ('bank', 'Bank Account Verification'), ('driving_license', 'Driving License Verification'), ('voter_id', 'Voter ID Verification'), ('passport', 'Passport Verification'), ('gst', 'GST Verification'), ('cin', 'CIN Verification'), ('ifsc', 'IFSC Verification'), ('vehicle_rc', 'Vehicle RC Verification'), ('face_liveness', 'Face Liveness'), ('face_match', 'Face Match'), ('name_match', 'Name Match'), ('smart_ocr', 'Smart OCR'), ('phone', 'Phone Verification'), ('email', 'Email Verification'), ('test_connection', 'Test Connection')], db_index=True, help_text='Type of API call', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('failed', 'Failed')], db_index=True, help_text='API call status', max_length=20)),
                ('endpoint', models.CharField(help_text='API endpoint called', max_length=200)),
                ('method', models.CharField(default='POST', help_text='HTTP method', max_length=10)),
                ('request_payload', models.JSONField(blank=True, help_text='Request payload (sanitized)', null=True)),
                ('verification_id', models.CharField(blank=True, db_index=True, help_text='Cashfree verification ID', max_length=100, null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data from API', null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if call failed', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code from API', max_length=100, null=True)),
                ('error_type', models.CharField(blank=True, help_text='Error type', max_length=200, null=True)),
                ('traceback', models.TextField(blank=True, help_text='Error traceback', null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Request ID for tracing', max_length=100, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('log_entry', models.ForeignKey(blank=True, help_text='Related LogEntry for unified logging', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashfree_api_logs', to='portal.logentry')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the API call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashfree_api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashfree API Log',
                'verbose_name_plural': 'Cashfree API Logs',
                'db_table': 'portal_cashfree_api_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'status'], name='portal_cash_timesta_197902_idx'), models.Index(fields=['api_type', '-timestamp'], name='portal_cash_api_typ_3ee364_idx'), models.Index(fields=['user', '-timestamp'], name='portal_cash_user_id_e7705e_idx'), models.Index(fields=['verification_id'], name='portal_cash_verific_96e6e1_idx'), models.Index(fields=['status', '-timestamp'], name='portal_cash_status_c46ed0_idx')],
            },
        ),
    ]
