# Generated by Django 5.2.10 on 2026-01-26 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_add_kaleyra_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('cashfree_pg', 'Cashfree PG API'), ('kaleyra', 'Kaleyra API'), ('leegality', 'Leegality API'), ('gift_voucher', 'Gift Voucher'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
        migrations.CreateModel(
            name='GiftVoucherAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, help_text='Type of entity (brand, voucher, transaction, etc.)', max_length=50)),
                ('entity_id', models.BigIntegerField(db_index=True, help_text='ID of the entity')),
                ('action', models.CharField(help_text='Action performed', max_length=100)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='User ID who performed the action', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=255, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Old values before change')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values after change')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When audit log was created')),
            ],
            options={
                'verbose_name': 'Gift Voucher Audit Log',
                'verbose_name_plural': 'Gift Voucher Audit Logs',
                'db_table': 'portal_gift_voucher_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='portal_gift_entity__507567_idx'), models.Index(fields=['created_at'], name='portal_gift_created_71d3a9_idx'), models.Index(fields=['user_id'], name='portal_gift_user_id_676422_idx')],
            },
        ),
        migrations.CreateModel(
            name='GiftVoucherBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_code', models.CharField(db_index=True, help_text='Unique brand identifier code', max_length=20, unique=True)),
                ('brand_name', models.CharField(help_text='Brand name', max_length=255)),
                ('business_reg_no', models.CharField(blank=True, help_text='Business registration number', max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Business address', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', help_text='Brand status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_brands', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucher_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gift Voucher Brand',
                'verbose_name_plural': 'Gift Voucher Brands',
                'db_table': 'portal_gift_voucher_brand',
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, help_text='Unique reference number for tracking', max_length=50, unique=True)),
                ('voucher_code', models.CharField(db_index=True, help_text='16-digit unique voucher code (display format: XXXX-XXXX-XXXX-XXXX)', max_length=16, unique=True)),
                ('voucher_code_hash', models.CharField(help_text='Encrypted voucher code for storage', max_length=255)),
                ('pin_hash', models.CharField(help_text='Hashed PIN (bcrypt)', max_length=255)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original voucher amount', max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, help_text='Current available balance', max_digits=15)),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIALLY_REDEEMED', 'Partially Redeemed'), ('FULLY_REDEEMED', 'Fully Redeemed'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', help_text='Voucher status', max_length=20)),
                ('mobile_number', models.CharField(blank=True, db_index=True, help_text='Mobile number for OTP-based redemption', max_length=20, null=True)),
                ('pin_retry_count', models.IntegerField(default=0, help_text='Number of failed PIN attempts')),
                ('pin_blocked_until', models.DateTimeField(blank=True, help_text='Timestamp until which PIN is blocked', null=True)),
                ('last_pin_change', models.DateTimeField(blank=True, help_text='Timestamp of last PIN change', null=True)),
                ('pin_history', models.JSONField(blank=True, default=list, help_text='Hash of last 3 PINs (JSON array)')),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When voucher was issued')),
                ('last_transaction_at', models.DateTimeField(blank=True, help_text='Timestamp of last transaction', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional brand-specific data')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(help_text='Brand that issued this voucher', on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='portal.giftvoucherbrand')),
            ],
            options={
                'verbose_name': 'Gift Voucher',
                'verbose_name_plural': 'Gift Vouchers',
                'db_table': 'portal_gift_voucher',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkVoucherIssuanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_reference', models.CharField(db_index=True, help_text='Unique batch reference number', max_length=50, unique=True)),
                ('total_vouchers', models.IntegerField(help_text='Total number of vouchers in batch')),
                ('processed_vouchers', models.IntegerField(default=0, help_text='Number of vouchers processed')),
                ('successful_vouchers', models.IntegerField(default=0, help_text='Number of successfully created vouchers')),
                ('failed_vouchers', models.IntegerField(default=0, help_text='Number of failed voucher creations')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Batch processing status', max_length=20)),
                ('uploaded_file_path', models.CharField(blank=True, help_text='Path to uploaded file (S3 or local)', max_length=500, null=True)),
                ('result_file_path', models.CharField(blank=True, help_text='Path to result file (S3 or local)', max_length=500, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When batch processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When batch processing completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When batch was created')),
                ('error_log', models.TextField(blank=True, help_text='Error log for failed processing', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_batches', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(help_text='Brand for this batch', on_delete=django.db.models.deletion.PROTECT, related_name='bulk_batches', to='portal.giftvoucherbrand')),
            ],
            options={
                'verbose_name': 'Bulk Voucher Issuance Batch',
                'verbose_name_plural': 'Bulk Voucher Issuance Batches',
                'db_table': 'portal_bulk_voucher_issuance_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftVoucherOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, help_text='Mobile number OTP was sent to', max_length=20)),
                ('otp_hash', models.CharField(help_text='Hashed OTP (bcrypt)', max_length=255)),
                ('otp_purpose', models.CharField(choices=[('REDEMPTION', 'Redemption'), ('PIN_CHANGE', 'PIN Change')], help_text='Purpose of OTP', max_length=20)),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP has been verified')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When OTP was generated')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When OTP expires')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was verified', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('voucher', models.ForeignKey(help_text='Voucher this OTP belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to='portal.giftvoucher')),
            ],
            options={
                'verbose_name': 'Gift Voucher OTP',
                'verbose_name_plural': 'Gift Voucher OTPs',
                'db_table': 'portal_gift_voucher_otp',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftVoucherTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ISSUANCE', 'Issuance'), ('REDEMPTION', 'Redemption'), ('BALANCE_INQUIRY', 'Balance Inquiry'), ('PIN_CHANGE', 'PIN Change')], db_index=True, help_text='Type of transaction', max_length=20)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Transaction amount (NULL for inquiry/PIN change)', max_digits=15, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Balance before transaction', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance after transaction', max_digits=15)),
                ('redemption_method', models.CharField(blank=True, choices=[('PIN', 'PIN'), ('OTP', 'OTP')], help_text='Redemption method used (for redemption transactions)', max_length=10, null=True)),
                ('transaction_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], help_text='Transaction status', max_length=20)),
                ('failure_reason', models.CharField(blank=True, help_text='Failure reason if transaction failed', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=255, null=True)),
                ('transaction_ref', models.CharField(blank=True, db_index=True, help_text='External transaction reference (unique)', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When transaction was created')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('voucher', models.ForeignKey(help_text='Voucher this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portal.giftvoucher')),
            ],
            options={
                'verbose_name': 'Gift Voucher Transaction',
                'verbose_name_plural': 'Gift Voucher Transactions',
                'db_table': 'portal_gift_voucher_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giftvoucherbrand',
            index=models.Index(fields=['brand_code'], name='portal_gift_brand_c_d600e6_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucherbrand',
            index=models.Index(fields=['status'], name='portal_gift_status_b3eb41_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['voucher_code'], name='portal_gift_voucher_249afa_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['reference_number'], name='portal_gift_referen_6b65ad_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['brand', 'status'], name='portal_gift_brand_i_9d6ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['status'], name='portal_gift_status_915c77_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['mobile_number'], name='portal_gift_mobile__a49ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkvoucherissuancebatch',
            index=models.Index(fields=['batch_reference'], name='portal_bulk_batch_r_250284_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkvoucherissuancebatch',
            index=models.Index(fields=['brand', 'status'], name='portal_bulk_brand_i_35df19_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkvoucherissuancebatch',
            index=models.Index(fields=['status'], name='portal_bulk_status_39b1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucherotp',
            index=models.Index(fields=['voucher', '-generated_at'], name='portal_gift_voucher_a3a394_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucherotp',
            index=models.Index(fields=['mobile_number'], name='portal_gift_mobile__0c2c47_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucherotp',
            index=models.Index(fields=['expires_at'], name='portal_gift_expires_98b11b_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvouchertransaction',
            index=models.Index(fields=['voucher', '-created_at'], name='portal_gift_voucher_087eca_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvouchertransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='portal_gift_transac_1e2668_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvouchertransaction',
            index=models.Index(fields=['created_at'], name='portal_gift_created_de12b3_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvouchertransaction',
            index=models.Index(fields=['transaction_ref'], name='portal_gift_transac_c167a3_idx'),
        ),
    ]
