# Generated by Django 5.2.10 on 2026-01-26 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_add_brand_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='batch_reference_number',
            field=models.CharField(blank=True, db_index=True, help_text='Additional batch reference number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='denomination_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Multi-denomination breakdown: {amount: quantity, successful, failed}'),
        ),
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='issuance_method',
            field=models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('MANUAL_BULK', 'Manual Bulk')], db_index=True, default='FILE_UPLOAD', help_text='Method used for issuance (File Upload or Manual Bulk)', max_length=20),
        ),
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued this batch (Admin/API Partner/Brand Owner)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_voucher_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='issuer_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('API_PARTNER', 'API Partner'), ('BRAND_OWNER', 'Brand Owner')], db_index=True, help_text='Type of issuer (Admin/API Partner/Brand Owner)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued this voucher (Admin/API Partner/Brand Owner)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='issuer_name',
            field=models.CharField(blank=True, help_text='Human-readable issuer name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='issuer_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('API_PARTNER', 'API Partner'), ('BRAND_OWNER', 'Brand Owner')], db_index=True, help_text='Type of issuer (Admin/API Partner/Brand Owner)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VoucherClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client name', max_length=255)),
                ('client_code', models.CharField(db_index=True, help_text='Unique client identifier code', max_length=50, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Is this the default Payswap client for the brand')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Client status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When client was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When client was last updated')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional client-specific data')),
                ('brand', models.ForeignKey(help_text='Brand this client belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='portal.giftvoucherbrand')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher Client',
                'verbose_name_plural': 'Voucher Clients',
                'db_table': 'portal_voucher_client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client this batch was issued for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_batches', to='portal.voucherclient'),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client this voucher was issued for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='portal.voucherclient'),
        ),
        migrations.AddIndex(
            model_name='bulkvoucherissuancebatch',
            index=models.Index(fields=['batch_reference_number'], name='portal_bulk_batch_r_a060f4_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkvoucherissuancebatch',
            index=models.Index(fields=['client', 'status'], name='portal_bulk_client__11ab20_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkvoucherissuancebatch',
            index=models.Index(fields=['issued_by', 'issuer_type'], name='portal_bulk_issued__db5a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkvoucherissuancebatch',
            index=models.Index(fields=['issuance_method'], name='portal_bulk_issuanc_86adcf_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['client', 'status'], name='portal_gift_client__add5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['issued_by', 'issuer_type'], name='portal_gift_issued__af2dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherclient',
            index=models.Index(fields=['client_code'], name='portal_vouc_client__21373a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherclient',
            index=models.Index(fields=['brand', 'status'], name='portal_vouc_brand_i_75519c_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherclient',
            index=models.Index(fields=['brand', 'is_default'], name='portal_vouc_brand_i_6249b6_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherclient',
            index=models.Index(fields=['status'], name='portal_vouc_status_0d2170_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucherclient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('brand', 'is_default'), name='unique_default_client_per_brand'),
        ),
    ]
