# Generated by Django 5.2.10 on 2026-01-26 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_add_voucher_client_and_issuer_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking processing task', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='processing_locked_at',
            field=models.DateTimeField(blank=True, help_text='When batch processing was locked/started', null=True),
        ),
        migrations.AddField(
            model_name='bulkvoucherissuancebatch',
            name='processing_locked_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated processing (lock holder)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_voucher_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
