# Generated by Django 5.2.10 on 2026-01-27 06:55

from django.db import migrations, models
from django.contrib.postgres.indexes import GinIndex


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_add_metadata_to_bulk_batch'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bulkvoucherissuancebatch',
            index=models.Index(fields=['status', '-created_at'], name='bulkbatch_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['brand', 'status', '-issued_at'], name='gv_brand_status_issued_idx'),
        ),
        # Phase 2.2: GIN index for metadata JSON field queries (metadata->>'batch_id')
        migrations.AddIndex(
            model_name='giftvoucher',
            index=GinIndex(fields=['metadata'], name='gv_metadata_gin_idx'),
        ),
    ]
