# Generated by Django 5.2.10 on 2026-01-27 07:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_add_reseller_partner_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerPartnerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('TIERED', 'Tiered Pricing')], default='PERCENTAGE', help_text='Type of pricing model', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base price for the service', max_digits=15)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Markup percentage (if pricing_type is PERCENTAGE)', max_digits=5)),
                ('fixed_markup', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed markup amount (if pricing_type is FIXED)', max_digits=15)),
                ('commission_type', models.CharField(choices=[('REVENUE_SHARE', 'Revenue Share'), ('MARKUP', 'Markup'), ('FIXED_COMMISSION', 'Fixed Commission')], default='REVENUE_SHARE', help_text='Type of commission model', max_length=20)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage (if commission_type is REVENUE_SHARE)', max_digits=5)),
                ('fixed_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed commission amount (if commission_type is FIXED_COMMISSION)', max_digits=15)),
                ('tiered_pricing', models.JSONField(blank=True, default=list, help_text="Tiered pricing structure: [{'min': 0, 'max': 1000, 'rate': 2.5}, ...]")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this pricing is active')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this pricing becomes effective')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When this pricing expires (null = never expires)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this pricing configuration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_pricing', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Reseller partner', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_configs', to='portal.resellerpartner')),
                ('service', models.ForeignKey(help_text='Service this pricing applies to', on_delete=django.db.models.deletion.CASCADE, related_name='partner_pricing', to='portal.service')),
            ],
            options={
                'verbose_name': 'Reseller Partner Pricing',
                'verbose_name_plural': 'Reseller Partner Pricing',
                'db_table': 'portal_reseller_partner_pricing',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'service', 'is_active'], name='portal_rese_partner_a29cbc_idx'), models.Index(fields=['is_active', 'effective_from'], name='portal_rese_is_acti_bbf26e_idx')],
                'unique_together': {('partner', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ResellerPartnerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_period_start', models.DateTimeField(help_text='Start of settlement period')),
                ('settlement_period_end', models.DateTimeField(help_text='End of settlement period')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue in period', max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Total commission earned', max_digits=15)),
                ('total_transactions', models.IntegerField(default=0, help_text='Total number of transactions')),
                ('settlement_amount', models.DecimalField(decimal_places=2, help_text='Amount to be settled', max_digits=15)),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Settlement status', max_length=20)),
                ('settlement_reference', models.CharField(blank=True, help_text='Settlement reference number', max_length=255, null=True, unique=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (NEFT, IMPS, UPI, etc.)', max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Settlement notes', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional settlement data')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When settlement was processed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When settlement was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this settlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Reseller partner', on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='portal.resellerpartner')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed this settlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseller Partner Settlement',
                'verbose_name_plural': 'Reseller Partner Settlements',
                'db_table': 'portal_reseller_partner_settlement',
                'ordering': ['-settlement_period_end', '-created_at'],
                'indexes': [models.Index(fields=['partner', 'status', '-settlement_period_end'], name='portal_rese_partner_18cc0c_idx'), models.Index(fields=['status', '-settlement_period_end'], name='portal_rese_status_ad34da_idx'), models.Index(fields=['settlement_reference'], name='portal_rese_settlem_cb427f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResellerPartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('COMMISSION', 'Commission'), ('SETTLEMENT', 'Settlement'), ('ADJUSTMENT', 'Adjustment'), ('REFUND', 'Refund'), ('CHARGEBACK', 'Chargeback')], db_index=True, help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=3)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission earned by partner', max_digits=15)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate used', max_digits=5, null=True)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Base amount before markup', max_digits=15, null=True)),
                ('markup_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Markup amount', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Transaction status', max_length=20)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='Reference ID (e.g., voucher code, payment ID)', max_length=255, null=True)),
                ('external_reference', models.CharField(blank=True, help_text="External reference (e.g., partner's transaction ID)", max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Transaction description', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data')),
                ('transaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Transaction date/time')),
                ('settled_at', models.DateTimeField(blank=True, help_text='When transaction was settled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(blank=True, help_text='API key used for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='portal.apikey')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_transactions', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Reseller partner', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portal.resellerpartner')),
                ('service', models.ForeignKey(blank=True, help_text='Service this transaction is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='portal.service')),
            ],
            options={
                'verbose_name': 'Reseller Partner Transaction',
                'verbose_name_plural': 'Reseller Partner Transactions',
                'db_table': 'portal_reseller_partner_transaction',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['partner', 'transaction_type', '-transaction_date'], name='portal_rese_partner_7144b8_idx'), models.Index(fields=['partner', 'status', '-transaction_date'], name='portal_rese_partner_1b9fb6_idx'), models.Index(fields=['service', '-transaction_date'], name='portal_rese_service_84d723_idx'), models.Index(fields=['transaction_date'], name='portal_rese_transac_1018aa_idx'), models.Index(fields=['reference_id'], name='portal_rese_referen_dd848e_idx')],
            },
        ),
    ]
