# Generated by Django 6.0.1 on 2026-02-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_add_service_cost_and_payment_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftvoucher',
            options={'ordering': ['-issued_at'], 'permissions': [('view_voucher_sensitive', 'Can view voucher PIN and sensitive details (e.g. mobile number)')], 'verbose_name': 'Gift Voucher', 'verbose_name_plural': 'Gift Vouchers'},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('cashfree_pg', 'Cashfree PG API'), ('kaleyra', 'Kaleyra API'), ('leegality', 'Leegality API'), ('mobikwik_bbps', 'Mobikwik BBPS API'), ('gift_voucher', 'Gift Voucher'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
    ]
