# Generated by Django 5.2.10 on 2026-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_add_service_category_safe'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailqueue',
            new_name='portal_emai_status_de2542_idx',
            old_name='portal_emai_status_8a0b0d_idx',
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Service category for orchestration (AEPS, DMT, BBPS, etc.)', max_length=50, null=True),
        ),
    ]
