# Generated by Django 5.2.10 on 2026-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_rename_portal_emai_status_8a0b0d_idx_portal_emai_status_de2542_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapi',
            name='purpose',
            field=models.CharField(blank=True, help_text='API purpose / one-line description for orchestration', max_length=255, null=True),
        ),
    ]
