# Generated by Django 6.0.1 on 2026-02-07 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_add_bbps_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, help_text='Vehicle registration number', max_length=32)),
                ('brand', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Optional vehicle photo', null=True, upload_to='connect/vehicles/')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary vehicle for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='connect_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connect Vehicle',
                'verbose_name_plural': 'Connect Vehicles',
                'db_table': 'portal_connect_vehicle',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique slug/code used in QR and URL', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(help_text='Vehicle this QR belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='portal.vehicle')),
            ],
            options={
                'verbose_name': 'Connect Vehicle QR Code',
                'verbose_name_plural': 'Connect Vehicle QR Codes',
                'db_table': 'portal_connect_vehicle_qrcode',
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', '-created_at'], name='portal_conn_user_id_97483e_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('user', 'registration_number'), name='portal_connect_vehicle_user_reg_unique'),
        ),
    ]
