# Generated by Django 5.2.10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_add_connect_vehicle_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkPeVoucherBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Available voucher balance in INR', max_digits=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parkpe_voucher_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ParkPe Voucher Balance',
                'verbose_name_plural': 'ParkPe Voucher Balances',
                'db_table': 'portal_parkpe_voucher_balance',
            },
        ),
        migrations.CreateModel(
            name='ParkPeVoucherTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=10)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('service_code', models.CharField(blank=True, help_text='e.g. BBPS, voucher_purchase', max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkpe_voucher_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ParkPe Voucher Transaction',
                'verbose_name_plural': 'ParkPe Voucher Transactions',
                'db_table': 'portal_parkpe_voucher_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='parkpevoucherbalance',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='parkpe_voucher_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='parkpevouchertransaction',
            index=models.Index(fields=['user', '-created_at'], name='portal_park_user_id_6a8c0a_idx'),
        ),
    ]
