# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_seed_parkpe_bbps_service_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(default=dict, help_text='Full Cashfree vehicle-rc API response')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(help_text='Vehicle this RC data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rc_data', to='portal.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle RC Data',
                'verbose_name_plural': 'Vehicle RC Data',
                'db_table': 'portal_connect_vehicle_rc_data',
            },
        ),
    ]
