# Generated by Django 5.2.10 on 2026-02-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_vehicle_type_rename_and_merge'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parkpepaymentorder',
            new_name='portal_park_user_id_3edfe8_idx',
            old_name='portal_park_user_id_8f2d1b_idx',
        ),
        migrations.RenameIndex(
            model_name='parkpepaymentorder',
            new_name='portal_park_status_21281d_idx',
            old_name='portal_park_status_9a3c2e_idx',
        ),
        migrations.RenameIndex(
            model_name='parkpevouchertransaction',
            new_name='portal_park_user_id_402a61_idx',
            old_name='portal_park_user_id_6a8c0a_idx',
        ),
        migrations.AlterField(
            model_name='parkpepaymentgatewayconfig',
            name='credential_key',
            field=models.CharField(blank=True, help_text='Razorpay: Key ID. Cashfree: App ID (x-client-id). Optional if using single merchant from .env (RAZORPAY_KEY_ID / CASHFREE_PG_CLIENT_ID).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parkpepaymentgatewayconfig',
            name='merchant_id',
            field=models.CharField(blank=True, help_text='Merchant identifier (e.g. MCH_001). Isse pata chalega ki is gateway+service ke liye kaun sa merchant account use ho raha hai.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('', ''), ('two_wheeler', 'Bike/Scooty'), ('four_wheeler', 'Private Car'), ('commercial', 'Commercial')], db_index=True, default='', help_text='Bike/Scooty, Private Car, or Commercial (auto/taxi/big vehicle)', max_length=20),
        ),
    ]
