# Generated by Django 5.2.10 on 2026-02-12 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_add_vehicle_rc_unlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectPredefinedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label_en', models.CharField(help_text='Button label (English)', max_length=128)),
                ('label_hi', models.CharField(blank=True, default='', max_length=128)),
                ('body_en', models.TextField(help_text='Message text sent (English)')),
                ('body_hi', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Connect Predefined Message',
                'verbose_name_plural': 'Connect Predefined Messages',
                'db_table': 'portal_connect_predefined_message',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ConnectThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_scanner_threads', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_threads', to='portal.vehicle')),
            ],
            options={
                'verbose_name': 'Connect Thread',
                'verbose_name_plural': 'Connect Threads',
                'db_table': 'portal_connect_thread',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConnectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('predefined', 'Predefined')], db_index=True, default='text', max_length=20)),
                ('body', models.TextField(help_text='Message content (for predefined, stored resolved body)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('predefined_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='portal.connectpredefinedmessage')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.connectthread')),
            ],
            options={
                'verbose_name': 'Connect Message',
                'verbose_name_plural': 'Connect Messages',
                'db_table': 'portal_connect_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='connectthread',
            constraint=models.UniqueConstraint(fields=('vehicle', 'scanner_user'), name='portal_connect_thread_vehicle_scanner_unique'),
        ),
        migrations.AddIndex(
            model_name='connectmessage',
            index=models.Index(fields=['thread', 'created_at'], name='portal_conn_thread__7960a6_idx'),
        ),
    ]
