# Generated by Django 6.0.1 on 2026-02-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0053_parkpe_bbps_favorites_and_saved_bills'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partnervendorassignment',
            name='pva_partner_svc_active_primary',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('api_explorer', 'API Explorer Tests'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('cashfree_pg', 'Cashfree PG API'), ('kaleyra', 'Kaleyra API'), ('leegality', 'Leegality API'), ('mobikwik_bbps', 'Mobikwik BBPS API'), ('gift_voucher', 'Gift Voucher'), ('connect_vehicle', 'Connect Vehicle'), ('parkpe_auth', 'ParkPe Auth'), ('parkpe_bbps', 'ParkPe BBPS'), ('parkpe_voucher', 'ParkPe Voucher'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('corporate', 'Corporate')], default='individual', max_length=20),
        ),
    ]
