# Generated by Django 6.0.1 on 2026-02-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0055_remove_deprecated_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpsoperator',
            name='circle',
            field=models.CharField(blank=True, db_index=True, help_text='Circle (cir) for View Bill / Mobikwik API – from Operators.xlsx Circle/cir column', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_code',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee'), ('super_distributor', 'Super Distributor'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('customer', 'Customer')], help_text='User role code (required)', max_length=20),
        ),
    ]
