# Generated by Django 6.0.1 on 2026-02-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0057_add_hub_vendor_cost_and_service_income_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubCostRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, max_length=30)),
                ('vendor_code', models.CharField(db_index=True, default='', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hub Cost Rate Config',
                'db_table': 'portal_hub_cost_rate_config',
                'unique_together': {('service_code', 'vendor_code')},
            },
        ),
    ]
