# Generated by Django 6.0.1 on 2026-02-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0058_add_hub_cost_rate_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubIncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(choices=[('bbps', 'BBPS'), ('voucher', 'Voucher')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Income in INR', max_digits=15)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Original txn amount if applicable', max_digits=15, null=True)),
                ('vendor_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('period_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_income_records', to='portal.resellerpartner')),
            ],
            options={
                'verbose_name': 'Hub Income Record',
                'verbose_name_plural': 'Hub Income Records',
                'db_table': 'portal_hub_income_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_code', 'period_date'], name='portal_hub__service_39ff05_idx')],
            },
        ),
    ]
