# Generated by Django 5.2.11 on 2026-04-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0061_connectcalllog_kaleyra_call_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantpayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('partner_txn_id', models.CharField(db_index=True, max_length=128)),
                ('vendor_reference', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='initiated', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instantpay_transactions', to='portal.resellerpartner')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instantpay_transactions', to='portal.apivendor')),
            ],
            options={
                'db_table': 'portal_instantpay_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner_txn_id'], name='portal_inst_partner_fb0304_idx'), models.Index(fields=['service_name', 'action'], name='portal_inst_service_8b4a35_idx'), models.Index(fields=['status', '-created_at'], name='portal_inst_status_81b024_idx')],
                'constraints': [models.UniqueConstraint(fields=('partner', 'partner_txn_id'), name='portal_instantpay_partner_txn_unique')],
            },
        ),
    ]
