# Generated by Django 5.2.11 on 2026-04-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0062_alter_logentry_category_instantpaytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('api_explorer', 'API Explorer Tests'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('cashfree_pg', 'Cashfree PG API'), ('kaleyra', 'Kaleyra API'), ('leegality', 'Leegality API'), ('mobikwik_bbps', 'Mobikwik BBPS API'), ('gift_voucher', 'Gift Voucher'), ('connect_vehicle', 'Connect Vehicle'), ('parkpe_auth', 'ParkPe Auth'), ('parkpe_bbps', 'ParkPe BBPS'), ('parkpe_voucher', 'ParkPe Voucher'), ('parkpe_payment', 'ParkPe Payment'), ('parkpe_connect', 'ParkPe Connect'), ('parkpe_dashboard', 'ParkPe Dashboard'), ('parkpe_fastag', 'ParkPe FASTag'), ('parkpe_challan', 'ParkPe Challan'), ('parkpe_general', 'ParkPe General'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
    ]
