# Generated by Django 5.2.11 on 2026-04-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0067_notificationeventrule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicepushtoken',
            new_name='portal_devi_user_id_359ee8_idx',
            old_name='portal_devi_user_id_8c84f1_idx',
        ),
        migrations.RenameIndex(
            model_name='devicepushtoken',
            new_name='portal_devi_app_pla_e93569_idx',
            old_name='portal_devi_app_pla_2714b5_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationaudiencerule',
            new_name='portal_noti_platfor_d78077_idx',
            old_name='portal_notif_platform_688f13_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationbanner',
            new_name='portal_noti_platfor_ef6837_idx',
            old_name='portal_notif_platform_fcf2f6_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationbanner',
            new_name='portal_noti_service_ad1d1c_idx',
            old_name='portal_notif_service_81e486_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationcampaign',
            new_name='portal_noti_campaig_a3d8e5_idx',
            old_name='portal_notif_campaign__998749_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationcampaign',
            new_name='portal_noti_event_k_6b7ab8_idx',
            old_name='portal_notif_event_k_dfbec3_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdeliverylog',
            new_name='portal_noti_channel_74955e_idx',
            old_name='portal_notif_channel_18d9d9_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdeliverylog',
            new_name='portal_noti_campaig_0bdb58_idx',
            old_name='portal_notif_campaign_f4bfaa_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationeventrule',
            new_name='portal_noti_event_k_8e9670_idx',
            old_name='portal_notif_event_k_00d938_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='portal_user_user_id_bac638_idx',
            old_name='portal_user_user_id_4cb00e_idx',
        ),
    ]
