# Generated by Django 5.2.11 on 2026-04-12 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0068_rename_portal_devi_user_id_8c84f1_idx_portal_devi_user_id_359ee8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('warn', 'Warn'), ('temp_block', 'Temporary Block'), ('perm_block', 'Permanent Block'), ('unblock', 'Unblock')], db_index=True, max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_moderation_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_moderation_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connect Moderation Action',
                'verbose_name_plural': 'Connect Moderation Actions',
                'db_table': 'portal_connect_moderation_action',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'created_at'], name='portal_conn_target__67b48a_idx'), models.Index(fields=['action', 'created_at'], name='portal_conn_action_9ebb09_idx')],
            },
        ),
    ]
