# Generated by Django 5.2.11 on 2026-04-12 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0070_passkeycredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('hub', 'Hub'), ('parkpe', 'ParkPe'), ('system', 'System')], db_index=True, default='system', max_length=16)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('change_summary', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_audit_logs_actor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_user_settings_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='portal_user_user_id_8c8d51_idx'), models.Index(fields=['source', 'created_at'], name='portal_user_source_bb4b1c_idx'), models.Index(fields=['action', 'created_at'], name='portal_user_action_307673_idx')],
            },
        ),
    ]
