# Generated by Django 5.2.11 on 2026-04-14 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0071_usersettingsauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_code',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee'), ('super_distributor', 'Super Distributor'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('customer', 'Customer'), ('fleet_admin', 'Fleet Admin'), ('fleet_manager', 'Fleet Manager'), ('fleet_operator', 'Fleet Operator'), ('fleet_dispatcher', 'Fleet Dispatcher')], help_text='User role code (required)', max_length=20),
        ),
        migrations.CreateModel(
            name='FleetWorkspaceInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('assigned_role_code', models.CharField(default='fleet_operator', help_text='Role code applied to the user when this request is approved in admin.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_interests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_workspace_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_fleet_workspace_interest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='portal_flee_user_id_d54d57_idx')],
            },
        ),
    ]
