# Generated by Django 5.2.11 on 2026-04-14 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0072_fleet_workspace_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetDriverRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_roster_memberships', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_roster_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_fleet_driver_roster',
                'indexes': [models.Index(fields=['manager', 'driver'], name='portal_flee_manager_9506fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('manager', 'driver'), name='uniq_portal_fleet_roster_manager_driver')],
            },
        ),
    ]
