# Generated by Django 5.2.11 on 2026-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0073_fleet_driver_roster'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='portal_connect_vehicle_user_reg_unique',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='connect_scope',
            field=models.CharField(choices=[('consumer', 'Consumer Connect (personal)'), ('fleet', 'Fleet workspace')], db_index=True, default='consumer', help_text='consumer = personal Connect app; fleet = fleet ops only (no mixing in APIs)', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('user', 'registration_number', 'connect_scope'), name='portal_connect_vehicle_user_reg_scope_unique'),
        ),
    ]
