# Generated by Django 5.2.11 on 2026-04-16 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0074_vehicle_connect_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rc_view_debit_reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='Voucher redemption / ParkPe DEBIT reference_id for RC_VIEW payment (for refunds and audit)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ServiceVoucherRefundCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_reference_id', models.CharField(db_index=True, help_text='Original transaction ref used for voucher redemption and ParkPe DEBIT row', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('service_code', models.CharField(db_index=True, default='RC_VIEW', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('refunded', 'Refunded'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('rc_reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_detail', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='auto_fetch_failed', help_text='auto_fetch_failed | manual (future)', max_length=32)),
                ('admin_narration', models.TextField(blank=True, default='')),
                ('credit_transaction_ref', models.CharField(blank=True, default='', help_text='GiftVoucherTransaction.transaction_ref for the refund credit line (unique)', max_length=100)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismiss_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_voucher_refund_cases_dismissed', to=settings.AUTH_USER_MODEL)),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_voucher_refunds_processed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_voucher_refund_cases', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_voucher_refund_cases', to='portal.vehicle')),
            ],
            options={
                'verbose_name': 'Service voucher refund case',
                'verbose_name_plural': 'Service voucher refund cases',
                'db_table': 'portal_service_voucher_refund_case',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='portal_serv_status_cc27d1_idx'), models.Index(fields=['service_code', 'status'], name='portal_serv_service_d8256e_idx')],
            },
        ),
    ]
