# Generated by Django 5.2.11 on 2026-04-16 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0075_service_voucher_refund_case_and_vehicle_debit_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, help_text='Lowercase logical code e.g. bbps, rc_view, voucher_purchase, partner_commission', max_length=50)),
                ('document_subtype', models.CharField(choices=[('b2c_receipt', 'B2C receipt'), ('b2b_commission', 'B2B commission')], db_index=True, default='b2c_receipt', max_length=32)),
                ('sac_or_hsn', models.CharField(blank=True, default='', help_text='SAC or HSN label for receipts', max_length=32)),
                ('gst_rate', models.DecimalField(decimal_places=4, default=0, help_text='Combined GST % (intra-state CGST+SGST derived as half each)', max_digits=7)),
                ('gst_inclusive', models.BooleanField(default=True, help_text='If true, input amount is tax-inclusive (typical B2C)')),
                ('is_gst_exempt', models.BooleanField(default=True)),
                ('is_pass_through', models.BooleanField(default=False, help_text='If true: no GST on Payswap share; receipt still shows customer amount')),
                ('tds_rate', models.DecimalField(blank=True, decimal_places=4, help_text='TDS % on taxable base (mainly B2B commission)', max_digits=7, null=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax service profile',
                'verbose_name_plural': 'Tax service profiles',
                'db_table': 'portal_tax_service_profile',
                'constraints': [models.UniqueConstraint(fields=('service_code', 'document_subtype'), name='portal_tax_profile_service_subtype_uniq')],
            },
        ),
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('b2c_receipt', 'B2C receipt'), ('credit_note', 'Credit note'), ('b2b_commission_invoice', 'B2B commission invoice')], db_index=True, max_length=40)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('reference_id', models.CharField(db_index=True, max_length=255)),
                ('service_code', models.CharField(db_index=True, max_length=50)),
                ('transaction_direction', models.CharField(blank=True, default='', help_text='credit or debit when tied to ParkPe voucher ledger', max_length=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parkpe_voucher_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_documents', to='portal.parkpevouchertransaction')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_documents', to='portal.resellerpartner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing document',
                'verbose_name_plural': 'Billing documents',
                'db_table': 'portal_billing_document',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['user', '-issued_at'], name='portal_bill_user_id_8940af_idx'), models.Index(fields=['partner', '-issued_at'], name='portal_bill_partner_542814_idx'), models.Index(fields=['service_code', '-issued_at'], name='portal_bill_service_204807_idx')],
            },
        ),
    ]
