# Generated by Django 5.2.11 on 2026-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0079_alter_connectmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Calendar expiry (null = legacy / no expiry enforced)', null=True),
        ),
        migrations.AddField(
            model_name='historicalgiftvoucher',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Calendar expiry (null = legacy / no expiry enforced)', null=True),
        ),
        migrations.AddField(
            model_name='parkpeserviceconfig',
            name='voucher_bbps_category_allowlist',
            field=models.JSONField(blank=True, default=None, help_text='Non-empty list: voucher BBPS pay allowed only for these BBPSOperator.category values (uppercase match). Null = no category filter.', null=True),
        ),
        migrations.AddField(
            model_name='parkpeserviceconfig',
            name='voucher_bbps_operator_allowlist',
            field=models.JSONField(blank=True, default=None, help_text='Non-empty list: voucher BBPS pay allowed only for these operator IDs (ParkPe sheet id / biller_id / op string as sent by client). Null = no operator filter.', null=True),
        ),
    ]
