# Generated by Django 5.2.11 on 2026-04-19 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0080_gift_voucher_expiry_and_bbps_allowlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectQrOnboardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(db_index=True, max_length=128)),
                ('is_new_user', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_qr_onboard_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_qr_onboard_logs', to='portal.vehicle')),
            ],
            options={
                'verbose_name': 'Connect QR Onboard Log',
                'verbose_name_plural': 'Connect QR Onboard Logs',
                'db_table': 'portal_connect_qr_onboard_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'qr_code'], name='portal_conn_created_2c353c_idx')],
            },
        ),
    ]
