# Generated by Django 5.2.11 on 2026-04-21 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0081_connect_qr_onboard_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkPeBBPSBillPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('operator_id', models.CharField(blank=True, default='', max_length=128)),
                ('bill_id', models.CharField(blank=True, default='', max_length=128)),
                ('consumer_id', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=32)),
                ('vendor', models.CharField(default='mobikwik', max_length=32)),
                ('last_vendor_status', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_phase', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('pay_response_json', models.JSONField(blank=True, null=True)),
                ('last_poll_json', models.JSONField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_status_check_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkpe_bbps_bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ParkPe BBPS bill payment record',
                'verbose_name_plural': 'ParkPe BBPS bill payment records',
                'db_table': 'portal_parkpe_bbps_bill_payment_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='portal_park_user_id_ccbc8d_idx')],
            },
        ),
    ]
