# Generated by Django 5.2.10 on 2026-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0082_parkpe_bbps_bill_payment_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='chain_step',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='1=app/client, 2=first vendor, higher=downstream', null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Ties client + vendor rows in one flow (often same as X-Request-ID)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='log_role',
            field=models.CharField(blank=True, choices=[('client', 'Client / app request'), ('vendor', 'Vendor API'), ('system', 'System / downstream')], help_text='Position in request chain', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('api', 'API'), ('api_explorer', 'API Explorer Tests'), ('auth', 'Authentication'), ('payment', 'Payment'), ('notification', 'Notification'), ('security', 'Security'), ('cashfree', 'Cashfree API'), ('cashfree_pg', 'Cashfree PG API'), ('kaleyra', 'Kaleyra API'), ('leegality', 'Leegality API'), ('mobikwik_bbps', 'Mobikwik BBPS API'), ('gift_voucher', 'Gift Voucher'), ('connect_vehicle', 'Connect Vehicle'), ('parkpe_auth', 'ParkPe Auth'), ('parkpe_bbps', 'ParkPe BBPS'), ('parkpe_voucher', 'ParkPe Voucher'), ('parkpe_payment', 'ParkPe Payment'), ('parkpe_connect', 'ParkPe Connect'), ('parkpe_dashboard', 'ParkPe Dashboard'), ('parkpe_fastag', 'ParkPe FASTag'), ('parkpe_challan', 'ParkPe Challan'), ('parkpe_general', 'ParkPe General'), ('instantpay', 'Instantpay API'), ('general', 'General')], db_index=True, default='general', help_text='Log category', max_length=20),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['correlation_id', 'chain_step', 'timestamp'], name='portal_log__correla_56bca6_idx'),
        ),
    ]
