# Generated by Django 5.2.10 on 2026-04-27 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0083_logentry_trace_instantpay"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkPeChallanRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vehicle_number", models.CharField(db_index=True, max_length=32)),
                ("challan_number", models.CharField(db_index=True, max_length=128)),
                ("challan_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("status", models.CharField(blank=True, db_index=True, default="pending", max_length=32)),
                ("state", models.CharField(blank=True, default="", max_length=16)),
                ("offence", models.TextField(blank=True, default="")),
                ("offence_date", models.CharField(blank=True, default="", max_length=64)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("penalty_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("currency", models.CharField(blank=True, default="INR", max_length=8)),
                ("vehicle_owner_name", models.CharField(blank=True, default="", max_length=255)),
                ("issuing_authority", models.CharField(blank=True, default="", max_length=255)),
                ("officer_name", models.CharField(blank=True, default="", max_length=255)),
                ("due_date", models.CharField(blank=True, default="", max_length=64)),
                ("payment_deadline", models.CharField(blank=True, default="", max_length=64)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parkpe_challans", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "ParkPe Challan Record",
                "verbose_name_plural": "ParkPe Challan Records",
                "db_table": "portal_parkpe_challan_record",
                "ordering": ["-last_seen_at", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="parkpechallanrecord",
            constraint=models.UniqueConstraint(fields=("user", "vehicle_number", "challan_number"), name="uniq_parkpe_challan_user_vehicle_number"),
        ),
        migrations.AddIndex(
            model_name="parkpechallanrecord",
            index=models.Index(fields=["user", "vehicle_number", "-last_seen_at"], name="portal_park_user_id_00ad52_idx"),
        ),
        migrations.AddIndex(
            model_name="parkpechallanrecord",
            index=models.Index(fields=["user", "status", "-updated_at"], name="portal_park_user_id_2643ab_idx"),
        ),
    ]
