# Generated by Django 5.2.11 on 2026-04-28 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0088_seed_parking_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingExitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('method', models.CharField(blank=True, choices=[('voucher', 'Voucher'), ('upi', 'UPI')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('cf_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cf_payment_session_id', models.CharField(blank=True, max_length=500)),
                ('upi_qr_data', models.TextField(blank=True, help_text='Raw UPI string / QR data for deep-link')),
                ('upi_link', models.CharField(blank=True, max_length=1000)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expire pending UPI orders after 15 min', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parking_exit_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingTransactionPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(help_text='bcrypt hash of 4–6 digit PIN', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parking_transaction_pin',
            },
        ),
        migrations.AlterModelOptions(
            name='historicalparkingbooking',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical parking booking', 'verbose_name_plural': 'historical parking bookings'},
        ),
        migrations.RenameIndex(
            model_name='parkingbooking',
            new_name='parking_boo_custome_b94d37_idx',
            old_name='parking_bkg_cust_status_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingbooking',
            new_name='parking_boo_slot_id_555af4_idx',
            old_name='parking_bkg_slot_status_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingbooking',
            new_name='parking_boo_booking_90b27c_idx',
            old_name='parking_bkg_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='parkinglocation',
            new_name='parking_loc_city_1c912a_idx',
            old_name='parking_loc_city_active_idx',
        ),
        migrations.RenameIndex(
            model_name='parkinglocation',
            new_name='parking_loc_latitud_02a7ae_idx',
            old_name='parking_loc_latlng_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingoperator',
            new_name='parking_ope_user_id_7a0666_idx',
            old_name='parking_op_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingoperator',
            new_name='parking_ope_locatio_138144_idx',
            old_name='parking_op_loc_role_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingslot',
            new_name='parking_slo_status_79fb76_idx',
            old_name='parking_slot_status_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingslot',
            new_name='parking_slo_zone_id_ab8859_idx',
            old_name='parking_slot_zone_status_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingtransaction',
            new_name='parking_tra_booking_c3651b_idx',
            old_name='parking_txn_bkg_status_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingtransaction',
            new_name='parking_tra_idempot_ae4246_idx',
            old_name='parking_txn_idem_idx',
        ),
        migrations.RenameIndex(
            model_name='parkpechallanrecord',
            new_name='portal_park_user_id_ab9529_idx',
            old_name='portal_park_user_id_00ad52_idx',
        ),
        migrations.RenameIndex(
            model_name='parkpechallanrecord',
            new_name='portal_park_user_id_f76950_idx',
            old_name='portal_park_user_id_2643ab_idx',
        ),
        migrations.RemoveField(
            model_name='giftvoucher',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='historicalgiftvoucher',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='parkpeserviceconfig',
            name='voucher_bbps_category_allowlist',
        ),
        migrations.RemoveField(
            model_name='parkpeserviceconfig',
            name='voucher_bbps_operator_allowlist',
        ),
        migrations.AddField(
            model_name='historicalkyc',
            name='document_file_keys',
            field=models.JSONField(blank=True, default=list, help_text='List of private S3 object keys for secure document access'),
        ),
        migrations.AlterField(
            model_name='historicalparkingbooking',
            name='booking_reference',
            field=models.CharField(db_index=True, help_text='Human-readable booking ref e.g. PKP-20240428-0001', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalparkingbooking',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set on checkout; may differ from estimate if overstay', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparkingbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalparkingbooking',
            name='vehicle_type',
            field=models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler'), ('ev', 'EV'), ('heavy_vehicle', 'Heavy Vehicle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalparkinglocation',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["covered","cctv","ev_charging","valet","toilet"]'),
        ),
        migrations.AlterField(
            model_name='historicalparkinglocation',
            name='geofence_polygon',
            field=models.JSONField(blank=True, default=dict, help_text='GeoJSON polygon of the parking boundary for entry geo-validation'),
        ),
        migrations.AlterField(
            model_name='historicalparkinglocation',
            name='hub_project_id',
            field=models.IntegerField(blank=True, help_text='rbac.Project PK — scopes operator assignments', null=True),
        ),
        migrations.AlterField(
            model_name='historicalparkinglocation',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalparkinglocation',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='{"open":"06:00","close":"23:00","247":false}'),
        ),
        migrations.AlterField(
            model_name='historicalparkinglocation',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Hub user who owns this parking facility', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkinglocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingoperator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingrate',
            name='overnight_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed overnight charge (22:00–06:00); null = regular rate', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkingrevenue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingtransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_code',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee'), ('super_distributor', 'Super Distributor'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('customer', 'Customer'), ('fleet_admin', 'Fleet Admin'), ('fleet_manager', 'Fleet Manager'), ('fleet_operator', 'Fleet Operator'), ('fleet_dispatcher', 'Fleet Dispatcher'), ('parking_owner', 'Parking Owner'), ('parking_manager', 'Parking Manager'), ('parking_attendant', 'Parking Attendant')], help_text='User role code (required)', max_length=20),
        ),
        migrations.AddField(
            model_name='parkingexitpayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_payments', to='portal.parkingbooking'),
        ),
        migrations.AddField(
            model_name='parkingexitpayment',
            name='parking_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_payment', to='portal.parkingtransaction'),
        ),
        migrations.AddField(
            model_name='parkingtransactionpin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking_tx_pin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='parkingexitpayment',
            index=models.Index(fields=['booking', 'status'], name='parking_exi_booking_249bba_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingexitpayment',
            index=models.Index(fields=['cf_order_id'], name='parking_exi_cf_orde_0e8ab6_idx'),
        ),
    ]
