# Generated by Django 5.2.11 on 2026-04-30 06:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0090_parkpe_challan_payment_and_saved_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FasTagGatewayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=20)),
                ('fastag_id', models.CharField(db_index=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('error', 'Error'), ('tailgating_suspect', 'Tailgating suspect')], default='received', max_length=30)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'fastag_gateway_event',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleFasTagMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(db_index=True, max_length=20)),
                ('fastag_issuer', models.CharField(default='npci', max_length=20)),
                ('fastag_id', models.CharField(db_index=True, max_length=100)),
                ('fastag_wallet_id', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_balance_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('balance_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_fastag_mapping',
            },
        ),
        migrations.RenameIndex(
            model_name='parkpechallanpayment',
            new_name='portal_park_user_id_afb502_idx',
            old_name='portal_park_user_id_2de136_idx',
        ),
        migrations.RenameIndex(
            model_name='parkpechallanpayment',
            new_name='portal_park_user_id_10f44b_idx',
            old_name='portal_park_user_id_7347e1_idx',
        ),
        migrations.RenameIndex(
            model_name='parkpechallanpayment',
            new_name='portal_park_challan_c768da_idx',
            old_name='portal_park_challan_5e7c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='parkpesavedvehicle',
            new_name='portal_park_user_id_6ea389_idx',
            old_name='portal_park_user_id_7e3f7f_idx',
        ),
        migrations.AddField(
            model_name='fastaggatewayevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastag_gateway_events', to='portal.parkinglocation'),
        ),
        migrations.AddField(
            model_name='fastaggatewayevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastag_events', to='portal.parkingsession'),
        ),
        migrations.AddField(
            model_name='vehiclefastagmapping',
            name='linked_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastag_mappings', to='portal.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclefastagmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fastag_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fastaggatewayevent',
            index=models.Index(fields=['gate_id', 'event_type', 'received_at'], name='fastag_gate_gate_id_42de57_idx'),
        ),
        migrations.AddIndex(
            model_name='fastaggatewayevent',
            index=models.Index(fields=['fastag_id'], name='fastag_gate_fastag__c9e886_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclefastagmapping',
            index=models.Index(fields=['vehicle_number'], name='vehicle_fas_vehicle_34d21f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclefastagmapping',
            index=models.Index(fields=['fastag_id'], name='vehicle_fas_fastag__3c964b_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclefastagmapping',
            constraint=models.UniqueConstraint(fields=('user', 'vehicle_number'), name='uniq_user_vehicle_fastag_reg'),
        ),
        migrations.AddConstraint(
            model_name='vehiclefastagmapping',
            constraint=models.UniqueConstraint(fields=('fastag_id',), name='uniq_vehicle_fastag_fastag_id'),
        ),
    ]
