# Generated by Django 5.2.11 on 2026-04-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0091_vehicle_fastag_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparkinglocation',
            name='location_code',
            field=models.CharField(blank=True, db_index=True, help_text='Stable code from ops (e.g. PKP-LOC-005) — sent by gate hardware', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalparkinglocation',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 secret for /api/parking/webhooks/fastag-scanner/', max_length=128),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='location_code',
            field=models.CharField(blank=True, db_index=True, help_text='Stable code from ops (e.g. PKP-LOC-005) — sent by gate hardware', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 secret for /api/parking/webhooks/fastag-scanner/', max_length=128),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='state',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('entered', 'Entered'), ('payment_pending', 'Payment pending'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('aborted', 'Aborted')], db_index=True, default='entered', max_length=30),
        ),
    ]
