"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
import sys

from corsheaders.defaults import default_headers as cors_default_headers
from core.config import payswap_config

# Suppress urllib3 InsecureRequestWarning when Cashfree sandbox is used (SDK may skip verify)
try:
    env = getattr(payswap_config, "CASHFREE_PG_ENVIRONMENT", "SANDBOX") or "SANDBOX"
    if str(env).upper() == "SANDBOX":
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
except Exception:
    pass

# Detect test run (pytest or manage.py test) so we can adjust settings for migrations
RUNNING_TESTS = 'test' in sys.argv or (len(sys.argv) > 0 and 'pytest' in sys.argv[0])


BASE_DIR = Path(__file__).resolve().parent.parent

# Custom User Model
AUTH_USER_MODEL = 'portal.User'

SECRET_KEY = payswap_config.get_secret_key()
DEBUG = payswap_config.DEBUG
V2_PLACEHOLDER_MODE = getattr(payswap_config, 'V2_PLACEHOLDER_MODE', False)
OTP_SEND_RATE_LIMIT = int(getattr(payswap_config, "OTP_SEND_RATE_LIMIT", 3))
PARKPE_REQUIRE_BILLING_ADDRESS = getattr(payswap_config, "PARKPE_REQUIRE_BILLING_ADDRESS", False)
NOTIFICATIONS_ENABLED = getattr(payswap_config, "NOTIFICATIONS_ENABLED", True)
NOTIFICATIONS_PUSH_ENABLED = getattr(payswap_config, "NOTIFICATIONS_PUSH_ENABLED", False)
NOTIFICATIONS_ROLLOUT_PERCENT = getattr(payswap_config, "NOTIFICATIONS_ROLLOUT_PERCENT", 100)
NOTIFICATIONS_RATE_LIMIT_PER_USER = getattr(payswap_config, "NOTIFICATIONS_RATE_LIMIT_PER_USER", 50)
FCM_PROJECT_ID = getattr(payswap_config, "FCM_PROJECT_ID", None)
FCM_SERVICE_ACCOUNT_PATH = getattr(payswap_config, "FCM_SERVICE_ACCOUNT_PATH", None)
_fcm_service_account_json = getattr(payswap_config, "FCM_SERVICE_ACCOUNT_JSON", None)
FCM_SERVICE_ACCOUNT_JSON = _fcm_service_account_json.get_secret_value() if _fcm_service_account_json else None
ALLOWED_HOSTS = list(payswap_config.allowed_hosts_list)
if 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')  # Django test client / management command tests
# In development, allow requests from any host (e.g. LAN IP) so runserver 0.0.0.0 works from other devices
if DEBUG and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('*')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for allauth
    # Third party apps
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    "django_filters",
    # Audit history (must be after auth so AUTH_USER_MODEL is available)
    "simple_history",
    # Django Allauth for social authentication
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.apple",
    # Local apps (portal must come after django.contrib.auth to override createsuperuser)
    "api",
    "portal.apps.PortalConfig",  # Use explicit app config to ensure command override
    "rbac.apps.RbacConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "core.csrf_middleware.CSRFExemptAPIMiddleware",  # CSRF for portal; exempt /api/ for Angular/API clients
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "portal.middleware.FleetPortalBlockMiddleware",  # Block fleet roles from portal session UI
    "rbac.middleware.HubContextMiddleware",  # X-Project-Code / X-Department-Code for Hub RBAC scoping
    "simple_history.middleware.HistoryRequestMiddleware",  # User attribution for django-simple-history (after auth)
    "allauth.account.middleware.AccountMiddleware",  # Required for django-allauth
    "api.middleware.request_id_middleware.RequestIDMiddleware",  # Request ID extraction
    "api.middleware.parkpe_action_audit_middleware.ParkPeActionAuditMiddleware",  # ParkPe service-wise action audit logs
    "api.v2.middleware.APIKeyIPWhitelistMiddleware",  # IP whitelisting for API keys
    "api.v2.middleware.APIKeyUsageLoggingMiddleware",  # API usage logging
    "portal.middleware.RequestLoggingMiddleware",  # Request logging - captures all requests
    "portal.middleware.ProfileCompletionMiddleware",  # Profile completion enforcement
    "portal.middleware.MFARequiredMiddleware",  # MFA enforcement
    "portal.middleware.SessionLockMiddleware",  # Redirect expired session to PIN unlock when applicable
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "portal" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "portal.context_processors.voucherx_context",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": payswap_config.get_database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = "en-us"
TIME_ZONE = payswap_config.TIMEZONE
USE_I18N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR / "staticfiles"]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================================
# LOGGING CONFIGURATION (FILE-SYSTEM ONLY FOR APPLICATION LOGS)
# Application logs go to files; logs must never affect DB transactions.
# No secrets in logs (PIN, OTP, API keys, tokens). Log reference_id, entity_id, user_id, action.
# ============================================================================
def _log_dir():
    d = BASE_DIR / 'logs'
    d.mkdir(parents=True, exist_ok=True)
    return d

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'json': {
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _log_dir() / 'app.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'json',
        },
        'finance_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _log_dir() / 'finance.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'json',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _log_dir() / 'security.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'json',
        },
        'audit_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _log_dir() / 'audit.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'json',
        },
        'email_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _log_dir() / 'email.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'json',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _log_dir() / 'error.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'json',
            'level': 'ERROR',
        },
    },
    'root': {
        'handlers': ['console', 'app_file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'portal': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': payswap_config.LOG_LEVEL,
            'propagate': False,
        },
        'portal.tasks': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': payswap_config.LOG_LEVEL,
            'propagate': False,
        },
        'portal.finance': {
            'handlers': ['console', 'finance_file', 'error_file'],
            'level': payswap_config.LOG_LEVEL,
            'propagate': False,
        },
        'portal.security': {
            'handlers': ['console', 'security_file', 'error_file'],
            'level': payswap_config.LOG_LEVEL,
            'propagate': False,
        },
        'portal.audit': {
            'handlers': ['console', 'audit_file', 'error_file'],
            'level': payswap_config.LOG_LEVEL,
            'propagate': False,
        },
        'portal.email': {
            'handlers': ['console', 'email_file', 'error_file'],
            'level': payswap_config.LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Email settings (certifi CA for STARTTLS — see portal.mail_backends.PayswapSMTPBackend)
EMAIL_BACKEND = "portal.mail_backends.PayswapSMTPBackend"
EMAIL_HOST = payswap_config.SMTP_HOST
EMAIL_PORT = payswap_config.SMTP_PORT
EMAIL_USE_TLS = payswap_config.SMTP_USE_TLS
EMAIL_HOST_USER = payswap_config.SMTP_USER
EMAIL_HOST_PASSWORD = payswap_config.get_smtp_password()
DEFAULT_FROM_EMAIL = payswap_config.SMTP_DEFAULT_FROM

# CORS settings
# In development, allow any origin so Angular (any port) can call /api/auth/login without "Http failure 0"
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []  # ignored when ALLOW_ALL_ORIGINS is True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = payswap_config.cors_allowed_origins_list
CORS_ALLOW_CREDENTIALS = payswap_config.CORS_ALLOW_CREDENTIALS
# Allow X-App header for Parkpe BBPS (product toggle: parkpe/payswap)
CORS_ALLOW_HEADERS = list(cors_default_headers) + [
    "x-app",
    "x-project-code",
    "x-department-code",
]

# Cache configuration (Redis)
CACHES = payswap_config.get_redis_config()

# Celery configuration
celery_config = payswap_config.get_celery_config()
CELERY_BROKER_URL = celery_config["broker_url"]
CELERY_RESULT_BACKEND = celery_config["result_backend"]
CELERY_TIMEZONE = celery_config["timezone"]

# Celery task settings
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 1800  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 1500  # 25 minutes
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Celery Beat periodic task schedule
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-voucher-otps': {
        'task': 'portal.tasks.cleanup_expired_voucher_otps',
        'schedule': 600,  # every 10 minutes
    },
    'unblock-pin-locked-vouchers': {
        'task': 'portal.tasks.unblock_pin_locked_vouchers',
        'schedule': 300,  # every 5 minutes
    },
    'reconcile-pending-parkpe-orders': {
        'task': 'portal.tasks.reconcile_pending_parkpe_orders',
        'schedule': 600,  # every 10 minutes
    },
    'scan-saved-vehicles-for-challans': {
        'task': 'portal.tasks.scan_saved_vehicles_for_challans',
        'schedule': 1800,  # every 30 minutes
    },
    'clean-old-logs-daily': {
        'task': 'portal.tasks.clean_old_logs',
        'schedule': crontab(hour=2, minute=0),  # daily at 2am
    },
    'expire-hub-assignments-hourly': {
        'task': 'hub_rbac.expire_hub_assignments',
        'schedule': crontab(minute=0),  # every hour at :00
    },
    'reconcile-pending-parking-transactions': {
        'task': 'portal.tasks.parking_reconcile.reconcile_pending_parking_transactions',
        'schedule': 60,
    },
}

# Celery worker pool settings
# Use 'solo' pool on macOS to avoid SIGSEGV issues with prefork
# For production on Linux, use 'prefork' or 'threads'
# Options: 'prefork', 'solo', 'threads', 'gevent', 'eventlet'
import sys
if sys.platform == 'darwin':  # macOS
    CELERY_WORKER_POOL = 'solo'  # Single process, no forking (safe for macOS)
else:
    CELERY_WORKER_POOL = 'prefork'  # Default for Linux

# REST Framework settings with versioning
REST_FRAMEWORK = {
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1", "v2"],
    "VERSION_PARAM": "version",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "connect_scan": "60/min",
        "connect_call": "10/min",
        "connect_scanner_verify": "30/hour",
        "auth_otp": "100/hour",
        "auth_login": "30/hour",
    },
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "EXCEPTION_HANDLER": "api.exceptions.api_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Simple JWT (access + refresh for API consumers)
# Access payload: user_id + role_code (+ parking_location_ids / fleet_role when applicable); refresh unchanged.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=payswap_config.JWT_ACCESS_TOKEN_LIFETIME),
    "REFRESH_TOKEN_LIFETIME": timedelta(seconds=payswap_config.JWT_REFRESH_TOKEN_LIFETIME),
    "SIGNING_KEY": payswap_config.get_jwt_signing_key(),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_REFRESH_SERIALIZER": "api.auth_parkpe.tokens.ParkPeTokenRefreshSerializer",
}

# Trusted proxy IPs for client IP resolution (VAPT-002/003). When REMOTE_ADDR is in this list,
# client IP is taken from X-Forwarded-For; otherwise X-Forwarded-For is ignored.
TRUSTED_PROXY_IPS = getattr(payswap_config, "trusted_proxy_ips_list", None) or []

# Connect risk controls (chat/call abuse prevention)
CONNECT_CALL_MAX_PER_USER_HOUR = int(os.getenv("CONNECT_CALL_MAX_PER_USER_HOUR", "8"))
CONNECT_CALL_MAX_PER_PHONE_HOUR = int(os.getenv("CONNECT_CALL_MAX_PER_PHONE_HOUR", "12"))
CONNECT_CALL_MAX_PER_OWNER_HOUR = int(os.getenv("CONNECT_CALL_MAX_PER_OWNER_HOUR", "15"))
CONNECT_CALL_MAX_PER_FINGERPRINT_HOUR = int(os.getenv("CONNECT_CALL_MAX_PER_FINGERPRINT_HOUR", "10"))
CONNECT_CALL_MAX_UNIQUE_QR_PER_HOUR = int(os.getenv("CONNECT_CALL_MAX_UNIQUE_QR_PER_HOUR", "5"))
CONNECT_CHAT_MAX_PER_USER_HOUR = int(os.getenv("CONNECT_CHAT_MAX_PER_USER_HOUR", "80"))
CONNECT_CHAT_MAX_PER_THREAD_HOUR = int(os.getenv("CONNECT_CHAT_MAX_PER_THREAD_HOUR", "35"))
CONNECT_CHAT_MAX_PER_RECIPIENT_HOUR = int(os.getenv("CONNECT_CHAT_MAX_PER_RECIPIENT_HOUR", "45"))
CONNECT_CHAT_MAX_PER_FINGERPRINT_HOUR = int(os.getenv("CONNECT_CHAT_MAX_PER_FINGERPRINT_HOUR", "100"))
CONNECT_CHAT_MAX_BODY_LENGTH = int(os.getenv("CONNECT_CHAT_MAX_BODY_LENGTH", "500"))
# Comma-separated extra Latin tokens for profanity gate (tests + custom ops list); see api/connect/profanity_filter.py
CONNECT_PROFANITY_EXTRA_TERMS = os.getenv("CONNECT_PROFANITY_EXTRA_TERMS", "")
_pprof_msg = os.getenv("CONNECT_PROFANITY_USER_MESSAGE", "").strip()
CONNECT_PROFANITY_USER_MESSAGE = _pprof_msg if _pprof_msg else None
_cp_custom = os.getenv("CONNECT_PROFANITY_CUSTOM_FILE", "").strip()
CONNECT_PROFANITY_CUSTOM_FILE = _cp_custom if _cp_custom else None
_cp_custom_hi = os.getenv("CONNECT_PROFANITY_CUSTOM_FILE_HI", "").strip()
CONNECT_PROFANITY_CUSTOM_FILE_HI = _cp_custom_hi if _cp_custom_hi else None
try:
    CONNECT_PROFANITY_AUTO_BLOCK_THRESHOLD = int(os.getenv("CONNECT_PROFANITY_AUTO_BLOCK_THRESHOLD", "0"))
except ValueError:
    CONNECT_PROFANITY_AUTO_BLOCK_THRESHOLD = 0
try:
    CONNECT_PROFANITY_AUTO_BLOCK_MINUTES = int(os.getenv("CONNECT_PROFANITY_AUTO_BLOCK_MINUTES", "60"))
except ValueError:
    CONNECT_PROFANITY_AUTO_BLOCK_MINUTES = 60
_ablk_msg = os.getenv("CONNECT_PROFANITY_AUTO_BLOCK_MESSAGE", "").strip()
CONNECT_PROFANITY_AUTO_BLOCK_MESSAGE = _ablk_msg if _ablk_msg else None

# API Documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "Payswap API",
    "DESCRIPTION": "Payswap API Documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
}

# Session Authentication Settings (web UI + Django Admin; does NOT affect API key auth)
# 15-minute inactivity timeout. User stays logged in while active; logged out after 15 min idle.
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_NAME = 'payswap_sessionid'
SESSION_COOKIE_AGE = 900  # 15 minutes (inactivity-based: expiry refreshes on every request)
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session expiry on any authenticated request → inactivity-based timeout
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF Settings
CSRF_COOKIE_NAME = 'payswap_csrftoken'
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for HTMX
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = payswap_config.cors_allowed_origins_list

# Login URLs
LOGIN_URL = '/signin/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Django Allauth Configuration
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Account Settings
# Allauth social/local methods (hub template sign-in also allows registered mobile via Profile).
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*']  # Required fields for signup
ACCOUNT_EMAIL_VERIFICATION = 'none'  # We handle email verification ourselves
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
# During tests, allauth's 0006_emailaddress_lower can run before portal.0004 in some
# migration orders; skip User email lowercasing in that migration to avoid FieldError.
ACCOUNT_USER_MODEL_EMAIL_FIELD = None if RUNNING_TESTS else 'email'
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGOUT_ON_GET = False

# Custom Allauth Adapter
SOCIALACCOUNT_ADAPTER = 'portal.adapters.CustomSocialAccountAdapter'

# Social Account Settings
SOCIALACCOUNT_AUTO_SIGNUP = False  # We handle signup ourselves
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # We handle verification
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = False  # Don't store OAuth tokens

# Social Provider Settings (from environment variables)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': payswap_config.GOOGLE_OAUTH_CLIENT_ID or '',
            'secret': str(payswap_config.GOOGLE_OAUTH_CLIENT_SECRET) if payswap_config.GOOGLE_OAUTH_CLIENT_SECRET else '',
            'key': ''
        }
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
            'email'
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
        'APP': {
            'client_id': payswap_config.FACEBOOK_OAUTH_APP_ID or '',
            'secret': str(payswap_config.FACEBOOK_OAUTH_APP_SECRET) if payswap_config.FACEBOOK_OAUTH_APP_SECRET else '',
            'key': ''
        }
    },
    'apple': {
        'APP': {
            'client_id': payswap_config.APPLE_OAUTH_CLIENT_ID or '',
            'secret': str(payswap_config.APPLE_OAUTH_PRIVATE_KEY) if payswap_config.APPLE_OAUTH_PRIVATE_KEY else '',
            'key': payswap_config.APPLE_OAUTH_KEY_ID or '',
            'team': payswap_config.APPLE_OAUTH_TEAM_ID or '',
        }
    }
}

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True if not DEBUG else False
SECURE_HSTS_PRELOAD = True if not DEBUG else False

# Test Runner
TEST_RUNNER = 'core.test_runner.CustomTestRunner'

# ---------------------------------------------------------------------------
# django-simple-history (audit trail)
# Compatible: Django >= 4.2 / 5.x / 6.x, Python >= 3.10
# Middleware order: HistoryRequestMiddleware must be AFTER AuthenticationMiddleware
# ---------------------------------------------------------------------------
SIMPLE_HISTORY_REVERT_DISABLED = True  # RBI-style: no revert from admin; audit log is immutable
SIMPLE_HISTORY_HISTORY_ID_USE_UUID = False  # Use integer history_id (default) for indexing
SIMPLE_HISTORY_DATE_INDEX = True  # Index history_date for as_of() and time-range queries (default)
SIMPLE_HISTORY_ENABLED = True  # Set False to disable history recording (e.g. migrations, bulk scripts)

# Sentry settings
# Cashfree requires sentry-sdk<1.33.0, which is pinned in requirements.txt
# Skip Sentry on Python 3.14+: sentry-sdk's Django integration mutates signal receivers
# (assumes list) but Django returns a tuple on 3.14, causing TypeError.
_sentry_ok = sys.version_info < (3, 14)
if payswap_config.SENTRY_ENABLED and _sentry_ok:
    sentry_dsn = payswap_config.get_sentry_dsn()
    if sentry_dsn and sentry_dsn.strip():
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        integrations = [DjangoIntegration()]
        try:
            from sentry_sdk.integrations.celery import CeleryIntegration
            integrations.append(CeleryIntegration())
        except Exception:
            pass

        sentry_sdk.init(
            dsn=sentry_dsn.strip(),
            integrations=integrations,
            environment=payswap_config.SENTRY_ENVIRONMENT,
            traces_sample_rate=0.1,
            send_default_pii=False,
        )