"""
Write logs task - ONLY Celery task that writes logs
All logging in the project goes through this task
"""
from celery import shared_task
from typing import Optional, Dict, Any
from datetime import datetime
from pathlib import Path
import json
import logging
from django.conf import settings
from core.config import payswap_config
from portal.utils.logging_helper import sanitize_sensitive_data


# Configure log categories and file paths
LOG_CATEGORIES = {
    'api': 'api',
    'auth': 'auth',
    'payment': 'payment',
    'notification': 'notification',
    'security': 'security',
    'general': 'general'
}

# Get base log directory
BASE_LOG_DIR = Path(settings.BASE_DIR) / payswap_config.PAYSWAP_LOG_DIR


def get_log_file_path(category: str, date: Optional[datetime] = None) -> Path:
    """
    Get log file path for category and date
    
    Args:
        category: Log category
        date: Date for log file (defaults to today)
    
    Returns:
        Path to log file
    """
    if date is None:
        date = datetime.now()
    
    # Create category subdirectory
    category_dir = BASE_LOG_DIR / LOG_CATEGORIES.get(category, 'general')
    category_dir.mkdir(parents=True, exist_ok=True)
    
    # Filename: portal_{category}_{YYYY-MM-DD}.log
    date_str = date.strftime('%Y-%m-%d')
    filename = f"portal_{LOG_CATEGORIES.get(category, 'general')}_{date_str}.log"
    
    return category_dir / filename


def categorize_log(module_name: Optional[str] = None, url: Optional[str] = None) -> str:
    """
    Determine log category based on module name and URL
    
    Args:
        module_name: Module name (e.g., 'portal.views', 'api.v1.views')
        url: URL path (e.g., '/api/v1/auth/login')
    
    Returns:
        Log category string
    """
    # Check URL first
    if url:
        if '/api/' in url:
            return 'api'
        if any(x in url for x in ['/login', '/signup', '/signin', '/auth', '/mfa', '/password']):
            return 'auth'
        if any(x in url for x in ['/payment', '/wallet', '/transaction']):
            return 'payment'
        if any(x in url for x in ['/notification', '/sms', '/email', '/otp']):
            return 'notification'
        if any(x in url for x in ['/security', '/lockout', '/failed']):
            return 'security'
    
    # Check module name
    if module_name:
        if 'api' in module_name.lower():
            return 'api'
        if any(x in module_name.lower() for x in ['auth', 'login', 'signup', 'mfa']):
            return 'auth'
        if any(x in module_name.lower() for x in ['payment', 'wallet', 'transaction']):
            return 'payment'
        if any(x in module_name.lower() for x in ['notification', 'sms', 'email', 'otp']):
            return 'notification'
        if any(x in module_name.lower() for x in ['security', 'lockout']):
            return 'security'
    
    return 'general'


@shared_task(name='portal.tasks.write_logs', bind=True, max_retries=3)
def write_logs_task(
    self,
    log_level: str,
    message: str,
    module_name: Optional[str] = None,
    url: Optional[str] = None,
    request_id: Optional[str] = None,
    response_id: Optional[str] = None,
    user_id: Optional[int] = None,
    extra_data: Optional[Dict[str, Any]] = None,
    client_ip: Optional[str] = None,
    user_agent: Optional[str] = None,
    session_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Write log entry to categorized, auto-rotating log file
    This is the ONLY Celery task that writes logs in the entire project
    
    Args:
        log_level: Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        message: Log message
        module_name: Module where event is happening
        url: URL path (for API requests)
        request_id: Request ID (from API request)
        response_id: Response ID (generated by server for API response)
        user_id: User ID (optional)
        extra_data: Additional data (will be sanitized)
        client_ip: Client IP address (always included)
        user_agent: User agent string (always included)
        session_id: Session ID (always included)
    
    Returns:
        Dict with success status
    """
    try:
        # Determine log category
        category = categorize_log(module_name, url)
        
        # Get current timestamp
        now = datetime.now()
        date_str = now.strftime('%Y-%m-%d')
        time_str = now.strftime('%H:%M:%S.%f')
        timestamp_iso = now.isoformat() + 'Z'
        
        # Build log entry
        log_entry = {
            'date': date_str,
            'time': time_str,
            'timestamp': timestamp_iso,
            'log_level': log_level.upper(),
            'message': message,
            'module_name': module_name or 'unknown',
            'url': url,
            'request_id': request_id,
            'response_id': response_id,
            'client_ip': client_ip or 'unknown',
            'user_agent': user_agent or 'unknown',
            'session_id': session_id or 'unknown',
        }
        
        # Add user ID if provided
        if user_id:
            log_entry['user_id'] = user_id
        
        # Add extra data (sanitized)
        if extra_data:
            log_entry['extra_data'] = sanitize_sensitive_data(extra_data)
        
        # Convert to JSON
        log_json = json.dumps(log_entry, default=str, ensure_ascii=False)
        
        # Get log file path
        log_file = get_log_file_path(category, now)
        
        # Write to file (append mode)
        try:
            with open(log_file, 'a', encoding='utf-8') as f:
                f.write(log_json + '\n')
        except Exception as e:
            # If write fails, try to log to default location
            fallback_file = BASE_LOG_DIR / 'portal_general.log'
            try:
                with open(fallback_file, 'a', encoding='utf-8') as f:
                    f.write(log_json + '\n')
            except:
                # Last resort: use Python logging
                logger = logging.getLogger('portal.tasks.write_logs')
                logger.error(f'Failed to write log to file: {str(e)}')
                logger.error(f'Log entry: {log_json}')
        
        return {
            'success': True,
            'category': category,
            'log_file': str(log_file.relative_to(BASE_LOG_DIR))
        }
        
    except Exception as e:
        # Retry on failure
        raise self.retry(exc=e, countdown=10 * (2 ** self.request.retries))
