from django.urls import path
from .views import (
    AuthLoginView,
    AuthFleetLoginView,
    AuthPartnerLoginView,
    AuthParkingLoginView,
    AuthOTPRequestView,
    AuthOTPVerifyView,
    AuthRegisterView,
    AuthRegisterSendOTPView,
    AuthRegisterVerifyView,
    AuthProfileView,
    AuthLogoutView,
    AuthPinStatusView,
    AuthPinSetView,
    AuthPinVerifyView,
    AuthForgotPasswordView,
    AuthPasskeyStatusView,
    AuthPasskeyRegisterOptionsView,
    AuthPasskeyRegisterVerifyView,
    AuthPasskeyAuthOptionsView,
    AuthPasskeyAuthVerifyView,
    AuthPasskeyDisableView,
    AuthPasskeyCredentialsView,
    AuthPasskeyCredentialDetailView,
    AuthPasskeyRecoveryRequestOTPView,
    AuthPasskeyRecoveryVerifyOTPView,
    AuthSecurityOverviewView,
    AuthSessionsRevokeView,
    AuthSecurityActivityView,
)

urlpatterns = [
    path("login", AuthLoginView.as_view(), name="auth-parkpe-login"),
    path("fleet/login", AuthFleetLoginView.as_view(), name="auth-parkpe-fleet-login"),
    path("partner/login", AuthPartnerLoginView.as_view(), name="auth-parkpe-partner-login"),
    path("parking/login", AuthParkingLoginView.as_view(), name="auth-parkpe-parking-login"),
    path("otp/request", AuthOTPRequestView.as_view(), name="auth-parkpe-otp-request"),
    path("otp/verify", AuthOTPVerifyView.as_view(), name="auth-parkpe-otp-verify"),
    path("register/send-otp", AuthRegisterSendOTPView.as_view(), name="auth-parkpe-register-send-otp"),
    path("register/verify", AuthRegisterVerifyView.as_view(), name="auth-parkpe-register-verify"),
    path("register", AuthRegisterView.as_view(), name="auth-parkpe-register"),
    path("profile", AuthProfileView.as_view(), name="auth-parkpe-profile"),
    path("logout", AuthLogoutView.as_view(), name="auth-parkpe-logout"),
    path("pin/status", AuthPinStatusView.as_view(), name="auth-parkpe-pin-status"),
    path("pin/set", AuthPinSetView.as_view(), name="auth-parkpe-pin-set"),
    path("pin/verify", AuthPinVerifyView.as_view(), name="auth-parkpe-pin-verify"),
    path("passkey/status", AuthPasskeyStatusView.as_view(), name="auth-parkpe-passkey-status"),
    path("passkey/register/options", AuthPasskeyRegisterOptionsView.as_view(), name="auth-parkpe-passkey-register-options"),
    path("passkey/register/verify", AuthPasskeyRegisterVerifyView.as_view(), name="auth-parkpe-passkey-register-verify"),
    path("passkey/auth/options", AuthPasskeyAuthOptionsView.as_view(), name="auth-parkpe-passkey-auth-options"),
    path("passkey/auth/verify", AuthPasskeyAuthVerifyView.as_view(), name="auth-parkpe-passkey-auth-verify"),
    path("passkey/disable", AuthPasskeyDisableView.as_view(), name="auth-parkpe-passkey-disable"),
    path("passkey/credentials", AuthPasskeyCredentialsView.as_view(), name="auth-parkpe-passkey-credentials"),
    path("passkey/credentials/<int:credential_id>", AuthPasskeyCredentialDetailView.as_view(), name="auth-parkpe-passkey-credential-detail"),
    path("passkey/recovery/request-otp", AuthPasskeyRecoveryRequestOTPView.as_view(), name="auth-parkpe-passkey-recovery-request-otp"),
    path("passkey/recovery/verify-otp", AuthPasskeyRecoveryVerifyOTPView.as_view(), name="auth-parkpe-passkey-recovery-verify-otp"),
    path("security-overview", AuthSecurityOverviewView.as_view(), name="auth-parkpe-security-overview"),
    path("sessions/revoke", AuthSessionsRevokeView.as_view(), name="auth-parkpe-sessions-revoke"),
    path("security-activity", AuthSecurityActivityView.as_view(), name="auth-parkpe-security-activity"),
    path("forgot-password", AuthForgotPasswordView.as_view(), name="auth-parkpe-forgot-password"),
]
