"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
from core.config import payswap_config


BASE_DIR = Path(__file__).resolve().parent.parent

# Custom User Model
AUTH_USER_MODEL = 'portal.User'

SECRET_KEY = payswap_config.get_secret_key()
DEBUG = payswap_config.DEBUG
ALLOWED_HOSTS = payswap_config.allowed_hosts_list

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for allauth
    # Third party apps
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    # Django Allauth for social authentication
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.apple",
    # Local apps (portal must come after django.contrib.auth to override createsuperuser)
    "api",
    "portal.apps.PortalConfig",  # Use explicit app config to ensure command override
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Required for django-allauth
    "api.middleware.request_id_middleware.RequestIDMiddleware",  # Request ID extraction
    "portal.middleware.ProfileCompletionMiddleware",  # Profile completion enforcement
    "portal.middleware.MFARequiredMiddleware",  # MFA enforcement
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "portal" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": payswap_config.get_database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = "en-us"
TIME_ZONE = payswap_config.TIMEZONE
USE_I18N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR / "staticfiles"]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'json': {
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'portal.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'json',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'portal_errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'json',
            'level': 'ERROR',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'portal': {
            'handlers': ['console', 'file', 'error_file'],
            'level': payswap_config.LOG_LEVEL,
            'propagate': False,
        },
        'portal.tasks': {
            'handlers': ['console', 'file', 'error_file'],
            'level': payswap_config.LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = payswap_config.SMTP_HOST
EMAIL_PORT = payswap_config.SMTP_PORT
EMAIL_USE_TLS = payswap_config.SMTP_USE_TLS
EMAIL_HOST_USER = payswap_config.SMTP_USER
EMAIL_HOST_PASSWORD = payswap_config.get_smtp_password()
DEFAULT_FROM_EMAIL = payswap_config.SMTP_DEFAULT_FROM

# CORS settings
CORS_ALLOWED_ORIGINS = payswap_config.cors_allowed_origins_list
CORS_ALLOW_CREDENTIALS = payswap_config.CORS_ALLOW_CREDENTIALS

# Cache configuration (Redis)
CACHES = payswap_config.get_redis_config()

# Celery configuration
celery_config = payswap_config.get_celery_config()
CELERY_BROKER_URL = celery_config["broker_url"]
CELERY_RESULT_BACKEND = celery_config["result_backend"]
CELERY_TIMEZONE = celery_config["timezone"]

# Celery task settings
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 1800  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 1500  # 25 minutes
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Celery worker pool settings
# Use 'solo' pool on macOS to avoid SIGSEGV issues with prefork
# For production on Linux, use 'prefork' or 'threads'
# Options: 'prefork', 'solo', 'threads', 'gevent', 'eventlet'
import sys
if sys.platform == 'darwin':  # macOS
    CELERY_WORKER_POOL = 'solo'  # Single process, no forking (safe for macOS)
else:
    CELERY_WORKER_POOL = 'prefork'  # Default for Linux

# REST Framework settings with versioning
REST_FRAMEWORK = {
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1", "v2"],
    "VERSION_PARAM": "version",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # Override per-view as needed
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# API Documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "Payswap API",
    "DESCRIPTION": "Payswap API Documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Session Authentication Settings
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_NAME = 'payswap_sessionid'
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF Settings
CSRF_COOKIE_NAME = 'payswap_csrftoken'
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for HTMX
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = payswap_config.cors_allowed_origins_list

# Login URLs
LOGIN_URL = '/signin/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Django Allauth Configuration
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Account Settings
# Login only accepts username or email - mobile numbers are NOT accepted for login
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Allow both username and email, NOT mobile number
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*']  # Required fields for signup
ACCOUNT_EMAIL_VERIFICATION = 'none'  # We handle email verification ourselves
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGOUT_ON_GET = False

# Custom Allauth Adapter
SOCIALACCOUNT_ADAPTER = 'portal.adapters.CustomSocialAccountAdapter'

# Social Account Settings
SOCIALACCOUNT_AUTO_SIGNUP = False  # We handle signup ourselves
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # We handle verification
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = False  # Don't store OAuth tokens

# Social Provider Settings (from environment variables)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': payswap_config.GOOGLE_OAUTH_CLIENT_ID or '',
            'secret': str(payswap_config.GOOGLE_OAUTH_CLIENT_SECRET) if payswap_config.GOOGLE_OAUTH_CLIENT_SECRET else '',
            'key': ''
        }
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
            'email'
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
        'APP': {
            'client_id': payswap_config.FACEBOOK_OAUTH_APP_ID or '',
            'secret': str(payswap_config.FACEBOOK_OAUTH_APP_SECRET) if payswap_config.FACEBOOK_OAUTH_APP_SECRET else '',
            'key': ''
        }
    },
    'apple': {
        'APP': {
            'client_id': payswap_config.APPLE_OAUTH_CLIENT_ID or '',
            'secret': str(payswap_config.APPLE_OAUTH_PRIVATE_KEY) if payswap_config.APPLE_OAUTH_PRIVATE_KEY else '',
            'key': payswap_config.APPLE_OAUTH_KEY_ID or '',
            'team': payswap_config.APPLE_OAUTH_TEAM_ID or '',
        }
    }
}

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True if not DEBUG else False
SECURE_HSTS_PRELOAD = True if not DEBUG else False

# Test Runner
TEST_RUNNER = 'core.test_runner.CustomTestRunner'

# Sentry settings
if payswap_config.SENTRY_ENABLED:
    sentry_dsn = payswap_config.get_sentry_dsn()
    if sentry_dsn and sentry_dsn.strip():
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=sentry_dsn.strip(),
            integrations=[DjangoIntegration()],
            environment=payswap_config.SENTRY_ENVIRONMENT,
            traces_sample_rate=1.0,
        )