"""
Automated billing: GST Invoice, Settlement Statement, Commission Invoice.
Generates HTML/PDF and stores under PARTNER_INVOICES_DIR; optional email.
Used by management command generate_invoices and cron run_billing_cycle.
"""
import os
import logging
from datetime import datetime, timedelta
from decimal import Decimal
from typing import Optional, List, Tuple

from django.conf import settings
from django.template import Template, Context
from django.utils import timezone

from portal.models import ResellerPartner, ResellerPartnerSettlement, ResellerPartnerTransaction

logger = logging.getLogger(__name__)

INVOICE_HTML_TEMPLATE = """
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{{ doc_title }}</title></head>
<body style="font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
  <h1>{{ doc_title }}</h1>
  <p><strong>Period:</strong> {{ period }}</p>
  <p><strong>Partner:</strong> {{ partner.company_name }} ({{ partner.partner_code }})</p>
  <p><strong>Date generated:</strong> {{ generated_at }}</p>
  <hr/>
  {% if settlement %}
  <table style="width:100%%; border-collapse: collapse;">
    <tr><td style="border:1px solid #ccc; padding:8px;">Total Revenue</td><td style="border:1px solid #ccc; padding:8px;">{{ settlement.total_revenue }}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;">Total Commission</td><td style="border:1px solid #ccc; padding:8px;">{{ settlement.total_commission }}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;">Settlement Amount</td><td style="border:1px solid #ccc; padding:8px;">{{ settlement.settlement_amount }}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;">Status</td><td style="border:1px solid #ccc; padding:8px;">{{ settlement.status }}</td></tr>
    <tr><td style="border:1px solid #ccc; padding:8px;">Reference</td><td style="border:1px solid #ccc; padding:8px;">{{ settlement.settlement_reference|default:"—" }}</td></tr>
  </table>
  {% endif %}
  {% if gst_amount is not None %}
  <p><strong>GST amount:</strong> {{ gst_amount }}</p>
  {% endif %}
  <hr/>
  <p style="color:#666; font-size:12px;">Generated by Payswap Billing. This is a system-generated document.</p>
</body></html>
"""


def _invoice_dir() -> str:
    base = getattr(settings, "PARTNER_INVOICES_DIR", None)
    if base:
        return base
    return os.path.join(settings.MEDIA_ROOT, "partner_invoices")


def _ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def _render_html(
    doc_title: str,
    partner: ResellerPartner,
    period: str,
    settlement: Optional[ResellerPartnerSettlement] = None,
    gst_amount: Optional[Decimal] = None,
) -> str:
    t = Template(INVOICE_HTML_TEMPLATE)
    ctx = Context({
        "doc_title": doc_title,
        "partner": partner,
        "period": period,
        "generated_at": timezone.now().strftime("%Y-%m-%d %H:%M UTC"),
        "settlement": settlement,
        "gst_amount": gst_amount,
    })
    return t.render(ctx)


def _html_to_pdf(html: str) -> Optional[bytes]:
    try:
        from xhtml2pdf import pisa
        from io import BytesIO
        out = BytesIO()
        pisa.CreatePDF(html.encode("utf-8"), dest=out, encoding="utf-8")
        return out.getvalue()
    except Exception as e:
        logger.warning("xhtml2pdf not available or failed: %s", e)
        return None


def get_or_create_settlement_for_period(
    partner: ResellerPartner,
    period_start: datetime,
    period_end: datetime,
) -> Optional[ResellerPartnerSettlement]:
    """Get existing settlement for period or create one (no duplicate create)."""
    from portal.services.partner_accounting_service import PartnerAccountingService
    existing = ResellerPartnerSettlement.objects.filter(
        partner=partner,
        settlement_period_start=period_start,
        settlement_period_end=period_end,
    ).first()
    if existing:
        return existing
    try:
        return PartnerAccountingService.create_settlement(
            partner=partner,
            period_start=period_start,
            period_end=period_end,
            created_by=None,
        )
    except Exception as e:
        logger.exception("create_settlement failed for %s: %s", partner.partner_code, e)
        return None


def generate_partner_documents(
    partner: ResellerPartner,
    period: str,
    send_email: bool = False,
    pdf: bool = True,
) -> List[Tuple[str, str]]:
    """
    Generate GST Invoice, Settlement Statement, Commission Invoice for one partner and period.
    period: YYYY-MM
    Returns list of (doc_type, file_path) for generated files.
    """
    try:
        year, month = map(int, period.split("-"))
    except (ValueError, AttributeError):
        logger.warning("Invalid period %s; use YYYY-MM", period)
        return []
    period_start = timezone.make_aware(datetime(year, month, 1))
    if month == 12:
        period_end = timezone.make_aware(datetime(year + 1, 1, 1)) - timedelta(microseconds=1)
    else:
        period_end = timezone.make_aware(datetime(year, month + 1, 1)) - timedelta(microseconds=1)

    settlement = get_or_create_settlement_for_period(partner, period_start, period_end)
    if not settlement:
        logger.warning("No settlement for %s %s; skipping documents", partner.partner_code, period)
        return []

    base_dir = os.path.join(_invoice_dir(), str(partner.id))
    _ensure_dir(base_dir)
    generated = []

    # Commission / Settlement statement (same data, different title)
    for doc_type, title in [
        ("settlement", "Settlement Statement"),
        ("commission", "Commission Invoice"),
        ("invoice", "GST Invoice"),
    ]:
        gst = Decimal("0.00") if doc_type == "invoice" else None
        html = _render_html(
            doc_title=title,
            partner=partner,
            period=period,
            settlement=settlement,
            gst_amount=gst,
        )
        subdir = os.path.join(base_dir, doc_type)
        _ensure_dir(subdir)
        html_path = os.path.join(subdir, f"{period}.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        generated.append((doc_type, html_path))

        if pdf:
            pdf_bytes = _html_to_pdf(html)
            if pdf_bytes:
                pdf_path = os.path.join(subdir, f"{period}.pdf")
                with open(pdf_path, "wb") as f:
                    f.write(pdf_bytes)
                generated.append((f"{doc_type}_pdf", pdf_path))

    if send_email and partner.email:
        _send_invoice_email(partner, period, generated)
    return generated


def _send_invoice_email(partner: ResellerPartner, period: str, generated: List[Tuple[str, str]]) -> None:
    try:
        from django.core.mail import send_mail
        subject = f"Payswap Invoices for {period}"
        body = f"Dear {partner.company_name},\n\nPlease find your billing documents for {period}.\n\nGenerated files: " + ", ".join(
            p for _, p in generated
        )
        send_mail(
            subject=subject,
            message=body,
            from_email=settings.DEFAULT_FROM_EMAIL if hasattr(settings, "DEFAULT_FROM_EMAIL") else "noreply@payswap.in",
            recipient_list=[partner.email],
            fail_silently=True,
        )
    except Exception as e:
        logger.warning("Failed to email invoice to %s: %s", partner.email, e)


def run_billing_cycle(period: Optional[str] = None, email: bool = False, pdf: bool = True) -> dict:
    """
    Run full billing cycle for a month: ensure settlements, generate all partner documents.
    period: YYYY-MM (default: previous month).
    Returns counts: partners_processed, documents_generated, errors.
    """
    if not period:
        prev = timezone.now().replace(day=1) - timezone.timedelta(days=1)
        period = prev.strftime("%Y-%m")
    partners = ResellerPartner.objects.filter(status="ACTIVE")
    processed = 0
    docs = 0
    errors = 0
    for partner in partners:
        try:
            files = generate_partner_documents(partner, period, send_email=email, pdf=pdf)
            if files:
                processed += 1
                docs += len(files)
        except Exception as e:
            errors += 1
            logger.exception("Billing for %s failed: %s", partner.partner_code, e)
    return {"partners_processed": processed, "documents_generated": docs, "errors": errors, "period": period}
