"""
Write logs task - ONLY Celery task that writes logs
All logging in the project goes through this task
"""
from celery import shared_task
from typing import Optional, Dict, Any
from datetime import datetime
from pathlib import Path
import json
import logging
from django.conf import settings
from core.config import payswap_config
from portal.utils.logging_helper import sanitize_sensitive_data, sanitize_log_message
from portal.utils.logging_utils import categorize_log


# Configure log categories and file paths
LOG_CATEGORIES = {
    'api': 'api',
    'api_explorer': 'api_explorer',
    'auth': 'auth',
    'payment': 'payment',
    'notification': 'notification',
    'security': 'security',
    'cashfree': 'cashfree',
    'cashfree_pg': 'cashfree_pg',
    'kaleyra': 'kaleyra',
    'leegality': 'leegality',
    'mobikwik_bbps': 'mobikwik_bbps',
    'gift_voucher': 'gift_voucher',
    'connect_vehicle': 'connect_vehicle',
    'parkpe_auth': 'parkpe_auth',
    'parkpe_bbps': 'parkpe_bbps',
    'parkpe_voucher': 'parkpe_voucher',
    'parkpe_payment': 'parkpe_payment',
    'parkpe_connect': 'parkpe_connect',
    'parkpe_dashboard': 'parkpe_dashboard',
    'parkpe_fastag': 'parkpe_fastag',
    'parkpe_challan': 'parkpe_challan',
    'parkpe_general': 'parkpe_general',
    'general': 'general'
}

# Get base log directory
BASE_LOG_DIR = Path(settings.BASE_DIR) / payswap_config.PAYSWAP_LOG_DIR


def get_log_file_path(category: str, date: Optional[datetime] = None) -> Path:
    """
    Get log file path for category and date
    
    Args:
        category: Log category
        date: Date for log file (defaults to today)
    
    Returns:
        Path to log file
    """
    if date is None:
        date = datetime.now()
    
    # Create category subdirectory
    category_dir = BASE_LOG_DIR / LOG_CATEGORIES.get(category, 'general')
    category_dir.mkdir(parents=True, exist_ok=True)
    
    # Filename: portal_{category}_{YYYY-MM-DD}.log
    date_str = date.strftime('%Y-%m-%d')
    filename = f"portal_{LOG_CATEGORIES.get(category, 'general')}_{date_str}.log"
    
    return category_dir / filename


# Import categorize_log from utils to avoid duplication
from portal.utils.logging_utils import categorize_log


@shared_task(name='portal.tasks.write_logs', bind=True, max_retries=3)
def write_logs_task(
    self,
    log_level: str,
    message: str,
    module_name: Optional[str] = None,
    url: Optional[str] = None,
    request_id: Optional[str] = None,
    response_id: Optional[str] = None,
    user_id: Optional[int] = None,
    extra_data: Optional[Dict[str, Any]] = None,
    client_ip: Optional[str] = None,
    user_agent: Optional[str] = None,
    session_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Write log entry to categorized, auto-rotating log file
    This is the ONLY Celery task that writes logs in the entire project
    
    Args:
        log_level: Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        message: Log message
        module_name: Module where event is happening
        url: URL path (for API requests)
        request_id: Request ID (from API request)
        response_id: Response ID (generated by server for API response)
        user_id: User ID (optional)
        extra_data: Additional data (will be sanitized)
        client_ip: Client IP address (always included)
        user_agent: User agent string (always included)
        session_id: Session ID (always included)
    
    Returns:
        Dict with success status
    """
    try:
        # Determine log category (pass extra_data to help detect voucher operations)
        category = categorize_log(module_name, url, extra_data)
        
        # Get current timestamp
        now = datetime.now()
        date_str = now.strftime('%Y-%m-%d')
        time_str = now.strftime('%H:%M:%S.%f')
        timestamp_iso = now.isoformat() + 'Z'
        
        # VAPT-001: sanitize message so OTP/phone never reach file or DB
        safe_message = sanitize_log_message(message)
        # Build log entry
        log_entry = {
            'date': date_str,
            'time': time_str,
            'timestamp': timestamp_iso,
            'log_level': log_level.upper(),
            'message': safe_message,
            'module_name': module_name or 'unknown',
            'url': url,
            'request_id': request_id,
            'response_id': response_id,
            'client_ip': client_ip or 'unknown',
            'user_agent': user_agent or 'unknown',
            'session_id': session_id or 'unknown',
        }
        
        # Add user ID if provided
        if user_id:
            log_entry['user_id'] = user_id
        
        # Add extra data (sanitized)
        if extra_data:
            log_entry['extra_data'] = sanitize_sensitive_data(extra_data)
        
        # Convert to JSON
        log_json = json.dumps(log_entry, default=str, ensure_ascii=False)
        
        # Get log file path
        log_file = get_log_file_path(category, now)
        
        # Write to file (append mode)
        try:
            with open(log_file, 'a', encoding='utf-8') as f:
                f.write(log_json + '\n')
        except Exception as e:
            # If write fails, try to log to default location
            fallback_file = BASE_LOG_DIR / 'portal_general.log'
            try:
                with open(fallback_file, 'a', encoding='utf-8') as f:
                    f.write(log_json + '\n')
            except:
                # Last resort: use Python logging
                logger = logging.getLogger('portal.tasks.write_logs')
                logger.error(f'Failed to write log to file: {str(e)}')
                logger.error(f'Log entry: {log_json}')
        
        # Also save to database for internal log management
        try:
            from portal.models import LogEntry, User
            from django.utils import timezone
            
            # Extract exception type from extra_data if present
            exception_type = None
            traceback_data = None
            if extra_data:
                exception_type = extra_data.get('exception_type')
                traceback_data = extra_data.get('traceback')
            
            # Get user object if user_id provided
            user_obj = None
            if user_id:
                try:
                    user_obj = User.objects.get(id=user_id)
                except User.DoesNotExist:
                    pass
            
            # Create database log entry (sanitize extra_data and message - VAPT-001)
            sanitized_extra = sanitize_sensitive_data(extra_data) if extra_data else {}
            LogEntry.objects.create(
                timestamp=now,
                log_level=log_level.upper(),
                category=category,
                message=safe_message,
                module_name=module_name or 'unknown',
                url=url,
                request_id=request_id,
                response_id=response_id,
                user=user_obj,
                client_ip=client_ip,
                user_agent=user_agent,
                session_id=session_id,
                extra_data=sanitized_extra,
                traceback=traceback_data,
                exception_type=exception_type
            )
        except Exception as db_error:
            # Don't fail the entire logging if DB save fails
            # Log to file as fallback
            logger = logging.getLogger('portal.tasks.write_logs')
            logger.warning(f'Failed to save log to database: {str(db_error)}')
        
        return {
            'success': True,
            'category': category,
            'log_file': str(log_file.relative_to(BASE_LOG_DIR))
        }
        
    except Exception as e:
        # Retry on failure
        raise self.retry(exc=e, countdown=10 * (2 ** self.request.retries))
