# Generated by Django 6.0.1 on 2026-02-07 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('parkpe', 'Parkpe'), ('payswap', 'Payswap')], db_index=True, max_length=20)),
                ('product_slug', models.CharField(db_index=True, help_text='e.g. mobikwik_bbps, euronet_bbps – used in code to check if product is enabled', max_length=80)),
                ('name', models.CharField(help_text='Display name e.g. Mobikwik BBPS', max_length=150)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in admin UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Product',
                'verbose_name_plural': 'API Products',
                'db_table': 'api_management_api_product',
                'ordering': ['platform', 'display_order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='apidowntimeevent',
            new_name='api_managem_api_reg_82c8ed_idx',
            old_name='api_managem_api_reg_3a1f2b_idx',
        ),
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_managem_api_reg_379826_idx',
            old_name='api_managem_api_reg_1d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_managem_status__243344_idx',
            old_name='api_managem_status_7a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_managem_princip_f4fdb8_idx',
            old_name='api_managem_princip_9e8f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='apiregistry',
            new_name='api_managem_version_dafe5c_idx',
            old_name='api_managem_version_8b0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='apiregistry',
            new_name='api_managem_service_2c532d_idx',
            old_name='api_managem_service_2c0e8a_idx',
        ),
        migrations.AlterField(
            model_name='apidowntimeevent',
            name='threshold_trigger',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. failure_rate_pct, latency_p99_ms'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Sanitized request metadata'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Sanitized response metadata'),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='allowed_role_codes',
            field=models.JSONField(blank=True, default=list, help_text="Allowed role codes e.g. ['admin','user','retailer']. Empty = use min_role_hierarchy only."),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='api_name',
            field=models.CharField(help_text='Human-readable API name', max_length=150),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='endpoint',
            field=models.CharField(help_text='Path template e.g. /api/v1/bbps/billers/', max_length=500),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='frontend_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='{"app": "parkpe", "featureModule": "bbps", "actionKey": "listBillers"}'),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='min_role_hierarchy',
            field=models.IntegerField(blank=True, help_text='Minimum portal.Role.hierarchy_level (null = no hierarchy check)', null=True),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='module_name',
            field=models.CharField(db_index=True, help_text='Logical module name', max_length=100),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='rate_limit',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"scope": "user", "rate": "60/min"} or {"scope": "ip", "rate": "100/hour"}'),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='required_permissions',
            field=models.JSONField(blank=True, default=list, help_text="Django permission codenames e.g. ['portal.view_user']"),
        ),
        migrations.AlterField(
            model_name='apiregistry',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Service category (BBPS, Wallet, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apis', to='api_management.servicecategory'),
        ),
        migrations.AddIndex(
            model_name='apiproduct',
            index=models.Index(fields=['platform', 'enabled'], name='api_managem_platfor_8fe841_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiproduct',
            constraint=models.UniqueConstraint(fields=('platform', 'product_slug'), name='api_management_product_platform_slug_unique'),
        ),
    ]
