# Generated by Django 6.0.1 on 2026-02-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'rbac_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'rbac_project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HubRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_roles', to='rbac.department')),
                ('permissions', models.ManyToManyField(blank=True, related_name='hub_roles', to='auth.permission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_roles', to='rbac.project')),
            ],
            options={
                'verbose_name': 'Hub Role',
                'verbose_name_plural': 'Hub Roles',
                'db_table': 'rbac_hubrole',
                'ordering': ['department', 'project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserHubAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, help_text='E.g. Manager, Executive, Head', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hub_assignments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='rbac.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='rbac.project')),
                ('roles', models.ManyToManyField(blank=True, related_name='user_assignments', to='rbac.hubrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Hub Assignment',
                'verbose_name_plural': 'User Hub Assignments',
                'db_table': 'rbac_userhubassignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hubrole',
            constraint=models.UniqueConstraint(fields=('department', 'project', 'code'), name='rbac_hubrole_dept_proj_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='userhubassignment',
            constraint=models.UniqueConstraint(fields=('user', 'department', 'project'), name='rbac_assignment_user_dept_proj_unique'),
        ),
    ]
